### ISSUE TITLE
Hide rebase backup branches

### ISSUE THREAD

**Issue by pkernevez** [ForkIssues/Tracker#1035]
Hi,

Rebase backup branches is a useful feature to avoid to do reflog commands.
But it creates a lot of branches, and those branches create a lot of noise when doing several successive interactive rebases on a branch.

I seen 2 improvement for them:
1. Have an option to hide the backup branches (by default), so you can show them afterward if necessary
2. Remove automatically backup branches with more than X days or only keep the last x branches.

**Comment by DanPristupov** [comment]
Hi,

While I understand your point of view  I think we can't make those changes:

> Have an option to hide the backup branches (by default), so you can show them afterward if necessary

This will lead to even more mess. I think you should simply remove the backups when rebase is completed. Fork even allows to remove multiple branches at once. The best solution is to not create a mess (or clean it ASAP) instead of collecting it.

> Remove automatically backup branches with more than X days or only keep the last x branches.

Removing something without an explicit user prompt is a dangerous idea.

I think you can achieve what you want if you not create backups at all and use reflog when needed. In this way you will see intermediate rebase branches which will be garbage-collected in a month. This is what I do myself when perform a huge rebase as a series of small rebases.

**Comment by olets** [comment]
> I think you can achieve what you want if you not create backups

Does that mean there's a way to disable backup branches? I just started seeing them for the first time today. My cat has been on the keyboard a lot this week so maybe he turned it on, but I'm not seeing a way to turn it off.

**Comment by DanPristupov** [comment]
@olets 
<img width="753" alt="Screenshot 2021-02-11 at 23 38 05" src="https://user-images.githubusercontent.com/618115/107707523-49a5f400-6cc2-11eb-812e-932d1b00bd1d.png">

**Comment by olets** [comment]
Thanks for the fast reply! Yes the must have been the cat 😹
