### ISSUE TITLE
Diff show empty window

### ISSUE THREAD

**Issue by joaomneto** [ForkIssues/Tracker#112]
I'm using version 1.0.56.1

When doing an interactive rebase, if I have a conflict and click on the diff button (or spacebar) I get and empty window. I've configured the diff integration to work with kaleidoscope.

Should I use it only with filemerge? Does this mean I need xcode?

![screen shot 2017-09-30 at 16 32 52 1](https://user-images.githubusercontent.com/5557570/31047140-09506992-a5fd-11e7-94f9-78bc031c6304.png)

This is the only hurdle for me as yours is hands down the best git client available IMO. Thanks for your work!

**Comment by DanPristupov** [comment]
Hi @joaomneto. Thank you for the kind words.

Side-by-side view is just a preview of the selected file. Since the file has a conflict, there's nothing to show until it's resolved. What would you expect to see there when file has a conflict?

If you want to merge the file in the configured merger (in your case Kaleidoscope), you need to press 'Merge' in the following view.
![2017-09-30 at 18 08](https://user-images.githubusercontent.com/618115/31047412-851ad30c-a60a-11e7-8536-c81db38ffb67.png)

**Comment by joaomneto** [comment]
Thanks for the response. I misunderstood the funcionality. I thought the diff file would display the diff between the pre merged file in the workspace and the remote, and the merge button would perform non interactive git merge.

It's clear for me now! 👍
