### ISSUE TITLE
[Feature Request] Allow Fork to point to a symlink for git

### ISSUE THREAD

**Issue by james-rabbit** [ForkIssues/Tracker#116]
I have git installed using brew, which uses a symlink to specify the location.

When I add the symlink as a "Custom Git Instance" to Fork `/usr/local/bin/git`, it immediately followed it to the destination, `/usr/local/Cellar/git/2.14.1/bin/git`.

This works great but I would prefer if it didn't follow the symlink immediately, so that it is always using the same version of git that I am using on the command line, even after I update git.

**Comment by DanPristupov** [comment]
I don't even know how it happens that Fork finds out the original destination :). But I'll investigate this. As for now use the Forks git instance please. It's relatively fresh.

**Comment by ElfSundae** [comment]
@DanPristupov FYI https://developer.apple.com/documentation/appkit/nsopenpanel/1533625-resolvesaliases

**Comment by DanPristupov** [comment]
@ElfSundae Thank you, that's what I needed.

I'm going to release a private beta here on Issue Tracker this week. It will contain some brand new features and the symlink fix.

**Comment by ElfSundae** [comment]
Great 👍

**Comment by DanPristupov** [comment]
Fixed that in 1.0.58, could you try it please? https://github.com/ForkIssues/Tracker/issues/152

**Comment by ElfSundae** [comment]
Fixed 🎉

**Comment by tflo** [comment]
@DanPristupov 

Since the bundled git is a bit outdated, are there any known issues with using a current git (2.15) with Fork?

![screen shot 2017-11-09 at 10 30 16-pty-fs8](https://user-images.githubusercontent.com/1410282/32598182-5116d5c6-c539-11e7-8218-b76ac7e034f6.png)

It _seems_ to work fine so far but maybe there are problems I’m not aware of (?)

BTW, thanks for the great tool! I notice that I’m starting to prefer it over GitUp more and more often…

– Tom

**Comment by DanPristupov** [comment]
@tflo no breaking changes, as far as I know. Feel free to use it.

You are welcome :).
