### ISSUE TITLE
Push to origin/master instead of the defined new branch origin/go

### ISSUE THREAD

**Issue by papa-cool** [ForkIssues/Tracker#1191]
When I create a new local branch `go`, commit on it and click on push, Fork propose me to push on a new branch `origin/go`.
<img width="496" alt="Capture d’écran 2020-11-24 à 15 41 38" src="https://user-images.githubusercontent.com/1018806/100110026-c87e5400-2e6c-11eb-90ce-0bae94a755d3.png">

After validating the push, Fork push local commits from `go` branch to `origin/master` instead of `origin/go`.
<img width="479" alt="Capture d’écran 2020-11-24 à 15 41 52" src="https://user-images.githubusercontent.com/1018806/100110061-d16f2580-2e6c-11eb-91e2-ba18806f1b2e.png">

My app is up to date "Fork 2.0.4 is currently the newest version available."

This issue first occurs in november.

**Comment by DanPristupov** [comment]
Can you check, what branch is tracked by the 'go' branch? You can see this info in the toolbar over the branch item on the sidebar.

**Comment by DanPristupov** [comment]
Here is an example:
<img width="332" alt="Screen Shot 2020-11-24 at 16 13 47" src="https://user-images.githubusercontent.com/618115/100112891-0a5cc980-2e70-11eb-8668-ae5d88e9234c.png">

**Comment by papa-cool** [comment]
Hi @DanPristupov 
Thank you for your answer.

No branch are tracked by the `go` branch.
<img width="222" alt="Capture d’écran 2020-11-24 à 17 12 03" src="https://user-images.githubusercontent.com/1018806/100120572-5dd31580-2e78-11eb-8a21-2db682c5f7f2.png">

After the previous push on `origin/master`, the push window still proposes me to push on a new `branch origin/go`.

**Comment by DanPristupov** [comment]
Something is wrong here 🤔
The `go` branch on the sidebar shows 2↑ which means it **has** a tracking reference. The push dialog also shows that `go` has a tracking reference (otherwise the 'Create tracking reference' checkbox would be visible).

Can you open terminal and show output of the following command please?

`git for-each-ref refs/heads/go --format='%(objectname) %(refname) %(upstream)'`

Or I can create a debug Fork build with additional logging which will give us more info.

**Comment by papa-cool** [comment]
> Can you open terminal and show output of the following command please?
> 
> `git for-each-ref refs/heads/go --format='%(objectname) %(refname) %(upstream)'`
```
-> git for-each-ref refs/heads/go --format='%(objectname) %(refname) %(upstream)'
70656026c13ea77788b9c1b35daad667678f0d5e refs/heads/go refs/heads/master
```

**Comment by DanPristupov** [comment]
This means that local branch `go` tracks local branch `master`. A local branch tracks another local branch. I'm not sure how this happened in your, but this is the cause of the problem.

Did you do this intentionally? If not, run `git branch --unset-upstream go` in terminal and then everything must start working correctly.

**Comment by papa-cool** [comment]
Thank you @DanPristupov.
The local tracking branch was always setup when creating a new branch through the console due to my global config.
```
[branch]
	autosetupmerge = always
```
Since it didn't cause any issue until November, I guess it conflicts with a change in a recent release of Fork.
I removed this config to fix my problem.

**Comment by DanPristupov** [comment]
> I guess it conflicts with a change in a recent release of Fork.

Yes. Starting from 1.0.99 Fork respects the remote tracking reference. Basically now it behaves same way as `git push branch` which absolutely logical and intuitive. It uses the tracking reference by default, but allows to change the destination branch if needed.

The problem is that Fork UI doesn't expect a remote tracking reference to be a local branch (I didn't even know this is possible until today). This is why the Push dialog shows `(new)`, while in reality it must show... well, I don't know what it must show in this case :).

**Comment by papa-cool** [comment]
> The problem is that Fork UI doesn't expect a remote tracking reference to be a local branch (I didn't even know this is possible until today). This is why the Push dialog shows (new), while in reality it must show... well, I don't know what it must show in this case :).

I don't know either what should be displayed.

Two points seem unexpected to me.
- 'Create tracking reference' checkbox is not displayed when the selected branch in the Push dialog is not already tracked.
- if a local branch is tracked, commits are pushed to the tracking reference of this local branch (here 'origin/master') instead of the selected branch in the Push dialog (here 'new (origin/go)').

Even if I'm not blocked anymore by this issue, I guess other developers can face the same problem which can be critical in a CI/CD workflow.
