### ISSUE TITLE
Click on Local Changes is not recognized in full screen

### ISSUE THREAD

**Issue by willku1024** [ForkIssues/Tracker#1217]
Fork Version 2.1.2
Somehow, the button （Local Change）won't go down。
![image](https://user-images.githubusercontent.com/33169620/101753448-9710b400-3b0d-11eb-97be-391388ef88f6.png)

**Comment by DanPristupov** [comment]
This looks like a bug in fullscreen mode in MacOS BigSur. The top part of the LocalChanges button is probably overlapped by (invisible) toolbar. Clicks on the bottom part of the button work properly.

**Comment by DanPristupov** [comment]
This bug exists even in Finder.

Make Finder full screen, open additional tab (cmd+T) and try to expand/collapse 'Favorites' section on the sidebar. It will not work because toolbar invisibly overlaps it.

<img width="306" alt="Screenshot 2020-12-10 at 11 24 24" src="https://user-images.githubusercontent.com/618115/101760022-9d396d00-3ada-11eb-818e-ee175e818467.png">

Update: this also can be reproduced in Mail

**Comment by DanPristupov** [comment]
Looks like this bug has been fixed in MacOS 11.**1**

**Comment by willku1024** [comment]
Yes~
