### ISSUE TITLE
Fork does not update from 2.1.1. to 2.2

### ISSUE THREAD

**Issue by kevindmoore** [ForkIssues/Tracker#1241]
I've tried updating for on 2 different computers and it downloads but the update fails

**Comment by YesThatAllen** [comment]
Has updating worked in the past?

I had a couple of macs that wouldn't update, and couldn't reach https://fork.dev/ either.

Turns out a part of [Pow](http://pow.cx/) was left behind, and these [lines from their removal script](https://github.com/basecamp/pow/blob/56d5214055947db83e2f82a9a16175cf63c15cdf/uninstall.sh#L121-L122) helped:

```bash
# Remove /etc/resolver files that belonged to pow.
      grep -Rl 'generated by Pow' /etc/resolver/ | sudo xargs rm
```

**Comment by kevindmoore** [comment]
Yes, I was able to update earlier. Seems this version has a problem

**Comment by YesThatAllen** [comment]
fwiw, I just setup a new computer, downloaded fork 2.1.1, installed it to `/Applications` and it auto-updated to 2.2.1 without issue.

**Comment by DanPristupov** [comment]
Can you download the update manually? https://cdn.fork.dev/mac/Fork-2.2.1.dmg

**Comment by kevindmoore** [comment]
Yes, that works. Although I think it goes around the problem of the updater not working.

**Comment by DanPristupov** [comment]
Do you have a problem updating to 2.3?

**Comment by kevindmoore** [comment]
So future updates have been fine. Once I just replaced that one version of
Fork, updating has been working.
Thanks,
Kevin Moore
