### ISSUE TITLE
Rebase “Edit” fails with “No branch name”

### ISSUE THREAD

**Issue by Tricertops** [ForkIssues/Tracker#1349]
Hi, I’m trying to edit one commit in interactive rebase, but it always fails with `No branch name` error.

Resolving merge conflicts always works for me during IR, but editing/amending does not. There is indeed no branch during IR, since I’m seeing bold **HEAD** in the side panel. The commit UI show big button for “Amend Last Commit” and there is a rebasing bar under the Tab Bar.

It’s trying to invoke this command:
```
$ git commit --amend --file=/var/folders/88/s1knvchd7kb4bx08x0fvnglc0000gn/T/81AB6498-7A36-42A1-8078-E56A1E1BCA57

No branch name.
```

Is there something wrong with my git setup or is this a Fork issue?

**Comment by Tricertops** [comment]
I’m not very good at CLI git, but I think it should invoke `$ git rebase --continue` instead.

**Comment by DanPristupov** [comment]
No, you need to amend. That's why you started IR with the **Edit** item after all. **Edit** stops and allows you to amend the latest commit.

After amending you can press Continue, which will run `git rebase --continue`.

I'm not sure why you see the `No branch name` error (I've never seen it, do you have hooks may be?). Can you try to amend the commit in CLI instead (`git commit --amend`) and then return to Fork, disable the `amend` checkbox and continue?

**Comment by Tricertops** [comment]
Hmm, okay I tried it in CLI and it threw the same error, so I was trying to look it up on the web, but nothing… then it clicked, you are right, the error is from a git hook in this repo 🤦🏻‍♂️
