### ISSUE TITLE
  Invalid/deinitialized submodules not listed

### ISSUE THREAD

**Issue by MerchV** [ForkIssues/Tracker#1441]
I use Fork as my primary Git client, but I was having trouble with my submodules so I opened the same repository with Tower and I noticed that the submodules were listed there are invalid. I just wanted to report it in case it's considered a bug or a possible improvement. 

<img width="435" alt="deinitialized-submodules" src="https://user-images.githubusercontent.com/778657/129099016-541e53b3-aa45-48f6-9a9c-f8eda5e02b34.png">

**Comment by DanPristupov** [comment]
What is a 'deinitialized' submodule?
Can you show the content of the `.gitmodules` file?

**Comment by MerchV** [comment]
I don't have a `.gitmodules` file, neither in the root of the repository, nor in the hidden `.git` directory.

What I did was I had 4 repositories that I grouped into a new repository as subdirectories, then I did a `git init` in the root directory, and I was confused about why Fork wasn't seeing into the subdirectories to add the files. I did some googling and I came across the command `git submodule deinit` which is why I called them deinitialized. 

I opened the root repository in Tower and it showed me a list of submodules and it allowed me to delete the submodule but keep the files, which is what I wanted. Then Fork was able to add the files in the subdirectories to the root repository.

**Comment by DanPristupov** [comment]
> I did some googling and I came across the command `git submodule deinit` which is why I called them deinitialized. 

I see now, thanks.
I just tried to create an empty repo, added a submodule and committed the changes. Then made `git submodule deinit`. The submodule data was removed, but the `.gitmodules` entry remained. Both `git submodule status` and Fork listed the submodule correctly.

> I don't have a .gitmodules file, neither in the root of the repository, nor in the hidden .git directory.

Then why do you think you have submodules? A submodule is something in the `.gitmodules` file, otherwise it's probably a subtree (?) which is a different git feature.

> I opened the root repository in Tower and it showed me a list of submodules and it allowed me to delete the submodule but keep the files, which is what I wanted.

May be I'm missing something, but what exactly it allowed to delete since you have no submodules (i.e. no `.gitmodules`), but only the files?

> I did a `git init` in the root directory, and I was confused about why Fork wasn't seeing into the subdirectories to add the files

You must have seen all subdirectories as local changes, I think.
