### ISSUE TITLE
Discarding changes to submodules does not work

### ISSUE THREAD

**Issue by jessetan** [ForkIssues/Tracker#148]
1. Checkout a project with a submodule
2. Make changes to the submodule on disk
3. Submodule is marked as containing changes
4. Under "Unstaged Files", choose "Discard Changes" from the rightclick context menu
5. Click "Discard File"
6. Nothing changes

Expected:
6. Changes are discarded and the submodule changes are reverted

Fork version 1.0.58.3

**Comment by DanPristupov** [comment]
Hi,

If I understood everything correctly, this is not a bug.

Submodules work like following: there are two repositories A and B. They are absolutely independent, but A contains a reference (sha) to HEAD in B (A -> B).

Then you made changes in B.
B* contains the changes themselves, and it's HEAD is different.
A contains an updated reference (because B tip points to a different thing now).

So, if you want to to discard changes in B, you need to open B (double click on the submodule on the sidebar) and discard them.

Please let me know if I'm missing something.

**Comment by DanPristupov** [comment]
However, we can introduce a feature there. Fork can recognise the submodule reference change and show a proposal like "Submodule 'xx' contains N changed. Are you sure you want to discard them all?".

Is that how you expected Fork to handle this case?

**Comment by jessetan** [comment]
I expect Fork to either do what you describe, or to not show a "Discard" option that does not do anything.

**Comment by DanPristupov** [comment]
@jessetan I see. Makes sense now. I didn't notice that the "Discard" option can be confusing.

**Comment by DanPristupov** [comment]
@jessetan yes, it's the same issue. I'm going to complete this task soon.
Actually it makes me think that we need to create a separate issue to discuss a plan for submodule improvements...

**Comment by DanPristupov** [comment]
Implemented the @jessetan original request in 1.0.62. Now it's possible to discard submodule changes by discarding its reference.
