### ISSUE TITLE
[macOS] No side-by-side option in staging area

### ISSUE THREAD

**Issue by Nezrahm** [ForkIssues/Tracker#1526]
We have the "side by side diff" option when looking at commits and on the Windows version do we also has this option in the staging area. On mac though this option in the staging is for some reason omitted.

**Comment by DanPristupov** [comment]
We are not satisfied how it works on Windows and that's why it's not on Mac (yet).

I think side-by-side layout is good for reviewing, not for editing.
It turned out that staging and unstaging becomes surprisingly confusing when a chunk is split into two text views.
Mouse selection also behaves weird because user can't select a contiguous piece of code anymore.
In sum, those issues lead to incorrect understanding of the diff concept and in its order makes people make worse commits.

**Comment by SimJoSt** [comment]
We had the same feature request.

Thanks for the response. I don't fully agree. The merge conflict resolution dialogue also uses a side by side view to decide what ends up in the final commit. So it is possible with a good feature set.  
I get, that this feature might be over kill for the staging view.

Sometimes it's a good idea to get inspired by other peoples work and to improve on it. In this instance I think the JetBrains PHPStorm staging interface with side-by-side view might be worth a look.

**Comment by Nezrahm** [comment]
Personally do I often do a lot of reviewing in the staging area to decide how to split up into multiple commits. So having the ability to view it like that is nice, then can you always switch back to the other view if you want to do complex partial staging.

**Comment by mwakerman** [comment]
+1

**Comment by DanPristupov** [comment]
> We are not satisfied how it works on Windows and that's why it's not on Mac (yet).

It took us a lot of work, but now side-by-side in the local changes view works the way we want.
It will be a part of the upcoming Fork `2.21` update.

If you are curious, you can try it already: https://cdn.fork.dev/prerelease/Fork-2.20.13.dmg.
