### ISSUE TITLE
Sidebar fold triangles are barely visible in Dark Theme

### ISSUE THREAD

**Issue by michaelconnor00** [ForkIssues/Tracker#16]
When using the Dark Theme, the small triangles for folding and unfolding content in the sidebar are barely visible. I have attached a screenshot. If I get really close to my screen I can see them, but from my normal viewing distance, they are not visible. 

![fork_tris](https://cloud.githubusercontent.com/assets/7796655/25397702/053a7626-299e-11e7-9c0c-552c25c267bf.png)

**Comment by DanPristupov** [comment]
I heard about this problem but could never reproduce it in my computer.

Now I just got an idea that the issue could be caused by Accessibility settings and I was right.
I'm going to investigate how to fix this, but as a workaround you can uncheck the 'Reduce Transparency' mode.

<img width="672" alt="2017-04-27 at 07 53" src="https://cloud.githubusercontent.com/assets/618115/25469824/05bbd05e-2b1f-11e7-98ff-3e6be2a69db8.png">

**Comment by aziz** [comment]
Sidebar blue highlights and grey highlights are wrong. They just look bad and if you compare it with an Apple app like finder,  you'll see what I mean. 
Finder does not use blue at all on the sidebar and their background highlight for the active section is a bit darker than what you're using in Fork.

**Comment by mhartung** [comment]
I do wish for a better solution and hence a better usability, because no matter if "reduce transparency" is activated or not, these triangles colors are to difficult to recognise.

**Comment by DanPristupov** [comment]
I fixed this bug in 1.0.53.
