### ISSUE TITLE
Multiple remotes with their own LFS storage result in errors when fetching

### ISSUE THREAD

**Issue by hybridherbst** [ForkIssues/Tracker#1639]
Related:
- https://github.com/git-lfs/git-lfs/issues/5025

Fork's workflow when multiple remotes have LFS is a bit weird:
- when fetching, Fork only fetches LFS from one remote
- fetching from the other remote will then usually error (when someone has added a new LFS file) since the file can't be found
- instead of rolling back, fork will keep all already fetched files staged, leading to confusion and potential user error (one needs to discard and then fetch again)

To reproduce:
- have a repository that uses LFS (on remoteA)
- push that repository to another remote that also uses LFS, make sure to push LFS files as well (remoteB)
- in Fork, make sure the order is "remoteA" then "remoteB"
- add LFS files and some non-LFS files to remoteB from another machine
- on the first machine, try to pull
- result: error with LFS files not being present as Fork will only fetch LFS from the first remote
- also result: non-LFS files are now uncommited changes (not rolled back after error) but commit is still on the old pointer

I think the solution is to call 
```
git lfs fetch remoteA
git lfs fetch remoteB
```
etc for all remotes, and then fetching actual data.

For now I have added an action that does just that as a workaround...

**Comment by DanPristupov** [comment]
> Fork's workflow when multiple remotes have LFS is a bit weird:

Fork just wraps git commands. Are you sure the problem is in Fork?

> when fetching, Fork only fetches LFS from one remote

When fetching or LFS fetching? If I remember correctly, git fetch should not make LFS fetch, but I might be wrong.

> on the first machine, try to pull
> result: error with LFS files not being present as Fork will only fetch LFS from the first remote

What happens when you run `git pull` in CLI?
You probably mean that pull **in git** doesn't update all LFS remotes properly? Is that related to Fork?

**Comment by hybridherbst** [comment]
Sorry, I don't have much experience in using git via command line besides the occasional thing that only works there. I'll try your suggestions / questions and update here.

**Comment by DanPristupov** [comment]
LFS is not part of git. It's a tool which stands on git hooks.

In git there is an ability to customize git behavior using hooks. Hooks are scripts in the `.git/hooks` directory which are run by git on some event. You can find some more info here https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks.

LFS uses hooks to sync its data. In particular:
- when you commit, `.git/hooks/pre-commit` will be called and LFS will replace the target files in your commit with LFS-pointers.
- when you checkout (merge, rebase, pull, etc), `.git/hooks/post-checkout` will be called and LFS will download the corresponding files and replace the pointers with the files.
- when you push, `.git/hooks/pre-push` will be called and LFS will upload required files.

So, first of all, try to reproduce the problem without Fork by running `git pull` in CLI. If the problem is not with Fork (currently it seems so), then we can proceed and create a small sample repo and show it to the guys from the GitLFS team.
