### ISSUE TITLE
Rebase on commits

### ISSUE THREAD

**Issue by Turbo87** [ForkIssues/Tracker#175]
It seems that there is currently no "Rebase" option in the context menu of commits. There is only "Interactive Rebase", which does what it's supposed to do, but the plain rebase seems to be missing.

**Comment by DanPristupov** [comment]
There is rebase. But it appears only for commits which have a branch. Same as merge.
![2017-12-15 at 13 31](https://user-images.githubusercontent.com/618115/34042313-5d14852e-e19c-11e7-89b6-2978b6978c49.png)

Interactive rebase is visible everywhere, because it allows you to reorder or reword commits within the current branch. So, interactive rebase on a commit is absolutely legitimate.

**Comment by Turbo87** [comment]
@DanPristupov that is exactly what I'm saying, but sometime I just want to rebase on top of a commit **without** reordering so I think making "Rebase" available on commits without a branch would make sense too

**Comment by DanPristupov** [comment]
@Turbo87 why don't you make an interactive rebase with default settings in this way?
BTW, what is the reason to rebase on a revision, not on a branch? From the top of the head I can't figure out why it can be useful.

I actually was thinking about removing rebase in the future, because it does the same as RI by default.

My point is to not introduce features which people rarely use. Clounie explained the idea here: https://github.com/ForkIssues/Tracker/issues/113

**Comment by Turbo87** [comment]
> why don't you make an interactive rebase with default settings in this way?

that is what I do, but it seems unnecessarily complex if all you want is a normal rebase

> what is the reason to rebase on a revision, not on a branch?

imagine you have two feature branches that share a few commits at the beginning. to bring them up-to-date with `master` you rebase `feature-a` on `master`, and then you would rebase `feature-b` on the last of the shared commits. if you rebase on `master` instead the commits won't be shared anymore due to the different timestamps and thus different hashes.

I'm not exactly sure what scenario I was in three days ago that required this rebase-on-commit, but it is something I regularly do and it seems unnecessary to me to restrict this to only work when rebasing on branches.

> I actually was thinking about removing rebase in the future, because it does the same as RI by default.

as I said above this makes the workflow more complicated since you need to confirm another dialog before being able to rebase. since 90% of the time a normal rebase is sufficient this seems to raise complexity instead of reducing it 🤔 

> My point is to not introduce features which people rarely use. Clounie explained the idea here: #113

I would agree, but I think rebasing is something a lot of people do very regularly. I'll comment in #113 about some other ideas to reduce the perceived complexity of the content menu.

**Comment by DanPristupov** [comment]
Just released 1.0.65 with ability to rebase on commits:
![2018-03-16 at 08 51](https://user-images.githubusercontent.com/618115/37509347-48d34742-28f7-11e8-97a5-5a58074bcb10.png)

**Comment by Turbo87** [comment]
Awesome, thanks a lot!
