### ISSUE TITLE
Ability to resolve conflicts manually

### ISSUE THREAD

**Issue by danez** [ForkIssues/Tracker#178]
Sometimes fork does not correctly recognize that all conflicts in a file have been resolved. When I try to click the Stage button nothing happens. If I instead do right-click->stage file gets staged and conflict resolved.

**Comment by tflo** [comment]
I think I had this issue too, a couple of days ago. Thanks for the right-click hint; will try it next time.

**Comment by DanPristupov** [comment]
Nowadays Fork just stages merge-conflict files automatically when their last-update time get changed. This approach works quite well with external merge tools, but can behave weirdly when a user resolves conflict manually.

Since you created the issue, I will add ability to resolve conflicts manually to my todo list.

**Comment by djdmbrwsk** [comment]
Awesome 👍 At the same time, I also noticed the diff in Fork didn't match the actual contents of the file.

Loving Fork by the way! Way cleaner and more performant than SourceTree.
