### ISSUE TITLE
Pulling with stash+rebase always throws submodule command error

### ISSUE THREAD

**Issue by nk1902** [ForkIssues/Tracker#1787]
When I pull from origin, an error message always shows up.

Looks like something is wrong with the submodule command that Fork is trying to call.

[screenshot](https://imgur.com/CvjJczJ)

**Comment by DanPristupov** [comment]
What git instance do you use in Fork?

**Comment by nk1902** [comment]
@DanPristupov 2.38.1

I've been seeing this error popup for a while now (at least a month)

**Comment by DanPristupov** [comment]
That's weird.

Is everything OK when you run `git pull` and `git submodule update` in command line? 
Do other commands (like checkout) work properly?

**Comment by nk1902** [comment]
Yes, all the commands work in CLI without errors.

Checkout and fetch works fine in Fork. It's just pull.

**Comment by DanPristupov** [comment]
Do you see any error when you select 'Update ...` in the submodule context menu on the sidebar?
Is 'Update submodules on checkout` enabled in Fork preferences? Try to change it.

**Comment by nk1902** [comment]
"Update submodules on checkout" was already selected in settings.

Checking out seems to work fine.

**Comment by dsbert** [comment]
I ran into this same issue. I'm pretty sure the linked bug report is the cause. You can test this by running the same command fork runs, without the `--verbose` flag.

https://lore.kernel.org/git/49a10767-8cdf-4c40-eb74-c7c61b80b7e7@cs-ware.de/T/

**Comment by DanPristupov** [comment]
@dsbert thank you!

As I see there's no fix yet, so we must wait for an update or downgrade git to `2.37.3`

**Comment by DanPristupov** [comment]
We releases `2.26.2` and rolled back the git update until a fix is released.

Once again, thank you very much @dsbert ❤️

**Comment by DanPristupov** [comment]
It's weird that you run into that error, because Fork doesn't pass `--recurse-submodules` to the `pull` command.

Did you define `submodule.recurse` manually in your global git config? If so, why?

You can check that by running `git config --show-origin submodule.recurse`.

**Comment by rdhzl** [comment]
I can say that in our case yes we do explicitly define that setting, and my understanding is that because we have a repo that currently (sadly) exists as a submodule to our primary repo, that this setting stages the sub-module repo where our code expects it. I'm not the most knowledgeable person on the subject on my team.

**Comment by DanPristupov** [comment]
@rdhzl I think this setting is excessive because Fork updates submodules automatically on pull/checkout.

**Comment by rdhzl** [comment]
@DanPristupov Gotcha. I think in our environment I'm the only person using Fork, and other people are using whatever else (console, Intellij, etc). I could probably unset that setting locally for Fork's sake, but I don't know if I'd break some other aspect of our env by doing so. Is it possible that Fork's auto-update could be a setting toggle in Fork?

**Comment by rdhzl** [comment]
Updated to latest (2.25.5) and not seeing error anymore. Thanks!

**Comment by hohwille** [comment]
> Updated to latest (2.25.5) and not seeing error anymore

As this was confusing me, here are my five cents:

Latest Fork-SCM version (windows) IMHO is 1.84.0.0 (dev channel)
Latest Git version (windows) is 2.40.1

After upgrading my Git version from 2.39.1 to 2.40.1 I could resolve the error:
You can then open `Preferences` in `git-fork` and go to `git` tab and switch `git instance` to the `2.40.1` one that you have installed rather than the `2.39.1` version from the build in git client of fork.
This fixed the error for me.

**Comment by DanPristupov** [comment]
@hohwille This topic is for Mac. Window issue tracker is here: https://github.com/fork-dev/TrackerWin/issues/1772
