### ISSUE TITLE
Offer to stash and reapply when doing interactive rebase and checkout commit

### ISSUE THREAD

**Issue by vrnvorona** [ForkIssues/Tracker#2034]
As title says. When I do regular rebase it's comfortable to have this option of stash and reapply. When I do interactive rebase I don't have this option sadly so it's not as convenient. Same goes for when i checkout commit on branch history

**Comment by DanPristupov** [comment]
Duplicate https://github.com/fork-dev/Tracker/issues/1268

**Comment by vrnvorona** [comment]
Sorry, it was a long lasting issue so I didn't found it. Hope one day it's implemented

**Comment by DanPristupov** [comment]
Most likely it won't.

Interactive rebase starts before the dialog is open. Thus, any uncommitted changes must be stashed **before** the IR dialog is open. Stashing changes without user confirmation is unacceptable.

**Comment by vrnvorona** [comment]
Well another dialog could be opened before IR one. Don't really understand how IR is different from regular rebase in this regard.

**Comment by DanPristupov** [comment]
> Don't really understand how IR is different from regular rebase in this regard.

The difference is that a regular rebase starts after the dialog is confirmed while IR starts before the dialog opens.

> Well another dialog could be opened before IR one.

Do you mean to show 'Do you want to stash your changes' dialog first and then after confirmation close it and open the 'IR' dialog?

**Comment by vrnvorona** [comment]
> Do you mean to show 'Do you want to stash your changes' dialog first and then after confirmation close it and open the 'IR' dialog?

Exactly

**Comment by angularsen** [comment]
Update: Cross-posted to #1268 since this was closed as a duplicate.


As a workaround, you can achieve this by configuring Git globally to autostash on rebase:

`git config --global rebase.autoStash true`

However, configuring globally may not be desired, so..
How about Fork offers an option in settings to always pass the `--autostash` flag on interactive rebase?

The regular rebase dialog has a checkbox to toggle this already, but since interactive rebase UI shows up after rebase is started, we need a separate option.

Regular rebase dialog:
![image](https://github.com/fork-dev/Tracker/assets/787816/b951714b-86ac-4ed2-81b0-a1a2524f333d)
