### ISSUE TITLE
Interactive rebase does not work when fork is installed in a directory with a space in the name

### ISSUE THREAD

**Issue by pwagland** [ForkIssues/Tracker#224]
If fork is installed into a directory with a space in the name, then interactive rebase doesn't work. It fails with a message like:

```
/usr/local/Cellar/git/2.16.2/libexec/git-core/git-rebase--interactive: line 267: /Applications/Local: No such file or directory
Could not execute editor
```

In my case, fork is installed in `/Applications/Local Applications`.

**Comment by DanPristupov** [comment]
@pwagland thank you for reporting the problem, going to investigate it.

**Comment by pwagland** [comment]
Even though this was not mentioned in the release notes, this seems to have been fixed in the 1.0.65.1 release?

**Comment by DanPristupov** [comment]
Thank you for spending your time testing that. I **did** update some suspicious places, but I didn't have a time to test it properly because moving all the XCode debug environment to a different directory is tricky.

I'm really glad that it works now.

So, I'm marking this issue as done and will check it in two weeks. If everything is ok, I'll close it. Until then, if you encounter any issue - please let me know.

**Comment by pwagland** [comment]
Two weeks later and it is still working for me :)
