### ISSUE TITLE
Fork offers to delete remotes which no longer exist

### ISSUE THREAD

**Issue by YesThatAllen** [ForkIssues/Tracker#321]
- Create a local brach:
- push to origin
- merge remote branch to its master
- delete remote branch
- Fetch & prune remote (which is my default action)
- delete local branch

Fork offers to delete the remote, although it's already been deleted. It could be improved to not show this option.

**Comment by DanPristupov** [comment]
Thank you for reporting that.

Yes, that's true. The local branch still has a tracking reference (which is invalid, because the remote one was removed).

There are two ways to improve that:
1. Do not show a 'delete remote' dialog (step 6) if local branch tracks an invalid branch
2. Offer to remote local branch when user deletes the local one (step 4).

I need to figure out.

**Comment by YesThatAllen** [comment]
Without proclaiming to be be a git master, git don't seem to remove the outdated tracking reference by default. To that end, I think option 1 makes more sense than option 2.

To this end, perhaps always showing "also remove remote" when the branch _had_ a remote, and graying out the choice when the remote isn't there. 
In any case, skipping this notice:

> error: unable to delete '[the branch name]': remote ref does not exist

would be 💯 

-----

If I use `git remote show origin` I can see that local branches which track outdated remote branches DO show in `Local branches configured for 'git pull'` but do not show in `Local refs configured for 'git push'`

This is true even after running the following as tests...

```
git fetch
git branch --merged
git branch -r
git fetch -p
git remote prune origin
```

So, yeah.. I guess it's fine/normal to leave the sale tracking reference. Having git-fork not fuss about it will be nice. Thanks!
