### ISSUE TITLE
Checking out a commit pointed to by a remote branch checks out local branch instead

### ISSUE THREAD

**Issue by jayrhynas** [ForkIssues/Tracker#338]
If I have a local branch that's ahead of a remote branch, and I try to check out the commit that the remote branch points to (by double clicking in the commit list), it will instead check out the local branch.

See screenshots for an example:

![screen shot 2018-07-13 at 9 21 45 pm](https://user-images.githubusercontent.com/1088234/42719423-36520780-86e3-11e8-9800-849218242175.png)
![screen shot 2018-07-13 at 9 23 26 pm](https://user-images.githubusercontent.com/1088234/42719426-389a68f2-86e3-11e8-8407-6ee59a252796.png)

**Comment by DanPristupov** [comment]
Double click provides the quick action with the following priority:
- if commit contains a local branch - check out the branch
- if commit contains a remote branch which has a tracking reference - check out the corresponding local branch
- if commit contains a remote branch without tracking reference - propose to create a tracking reference
- otherwise check out the commit

The checkout commit option is available in the context menu.

**Comment by jayrhynas** [comment]
Ok, I understand that logic. I guess I just expected double clicking on a specific commit to check out that commit, regardless of other local or remote branches pointing to that commit.

Thanks!
