### ISSUE TITLE
[Feature request] notate whitespace changes in the diff view

### ISSUE THREAD

**Issue by YesThatAllen** [ForkIssues/Tracker#340]
When there's a change in whitespace, the default view shows only red/green on a line:

![2018-07-14_09-40-19](https://user-images.githubusercontent.com/2879972/42725501-0abdef00-874a-11e8-9d1c-c7ddfaf2d4ab.png)

If I highlight the red / green change lines, I can see the difference a bit easier:

![2018-07-12_00-36-46](https://user-images.githubusercontent.com/2879972/42725510-26706cc8-874a-11e8-9aeb-956207bc5803.png)

If the whitespace had indicators for each space/tab/etc, it would be much easier to see what changed.

TIA!

**Comment by maksimovic** [comment]
+1

It's probably an edge case in my own case, but I'd be very happy if I could see a bite more "verbose" whitespace changes. The reason for it is that in one large monolith repository that I'm working on there are multiple conventions (don't ask... :D ) and sometimes the wrong indentation slips in, which I only notice a bit too late (e.g. when creating a PR or when it's already created). It always triggers at least some level of hate due to having to go back and hunt those down 😁

**Comment by DanPristupov** [comment]
I think this could be related https://github.com/ForkIssues/Tracker/issues/100

**Comment by DanPristupov** [comment]
I have a lot of tasks right now and then I'm having a vacation in 2 weeks. So, if I forget about this issue, please feel free to remind me.

**Comment by maksimovic** [comment]
A well deserved vacation, I guess!

I'd label this feature as a "nice to have", not something that you'd want to spend a lot of time on. I'm not sure if some external diff tool supports this, but this is so "important" to me that I've never bothered to even try something other than the default.

**Comment by YesThatAllen** [comment]
> I think this could be related #100 

It's not entirely clear what changes were being requested in that issue, so, maybe? Even in the gitx view, I don't see if the spacing changes were from tabs, spaces, etc. 

The change I'm looking for could be handled by using a monospace font that had built in • for spaces, etc.
