### ISSUE TITLE
SSH: Can't refresh Gitlab status

### ISSUE THREAD

**Issue by zarulizham** [ForkIssues/Tracker#347]
Cannot register SSH for Gitlab. I already add the .pub into Gitlab. Still same problem persist.

For Github seems no problem. Only for Gitlab.

![alt text](https://preview.ibb.co/jjoRjJ/Screen_Shot_2018_07_17_at_12_10_46_AM.png "Logo Title Text 1")

**Comment by luongvo209** [comment]
I can confirm this problem is happening. 
### Step to reproduce:
1. Sign in Gitlab in Fork with an access token
2. Add an SSH Key, either `system default` or some other key
3. See the "can't refresh gitlab status" show up.
### Expected result 
"SSH key configured correctly" as shown when log in with Github.

**Comment by DanPristupov** [comment]
Thank you for reporting this guys. GitLab has changed their API. I'm fixing this problem right now.

**Comment by zarulizham** [comment]
Looking forward for the new update soon 😘

**Comment by zarulizham** [comment]
Hello, is this bug not fixed yet for version 1.0.69.1?

**Comment by luongvo209** [comment]
Just about a week has passed. You have to give the developer some time, @zarulizham.

**Comment by desmond132518** [comment]
ok, so I am not the only one facing this issue.

**Comment by dKemen** [comment]
Is this issue already fixed in the latest version available on the website?

**Comment by desmond132518** [comment]
No. It just keeps saying "cannot refresh GitLab status".
