### ISSUE TITLE
Double clicking on a commit checks out a different commit.

### ISSUE THREAD

**Issue by BrianKenny** [ForkIssues/Tracker#354]
In the all commits view, when I double click on origin/master it checks out a different commit from about 2 months ago which is well offscreen.  If I right click and select checkout it works correctly, or if I double click on any other commit/branch it works correctly.   This started when I updated to version 1.0.69 (from an unknown version maybe 3 to 6 months earlier) on OSX 10.13.4.  The incorrect commit it checks out is consistent between attempts.  If I delete that branch it will consistently checkout a different incorrect brach from about the same time period.  The "Checkout" "Switches to another branch" alert shows the incorrect branch.  The bug occurs with fork's git instance and with system git selected in preferences(but git checkout origin/master works as expected in the terminal)

**Comment by DanPristupov** [comment]
Double click provides the quick action with the following priority:

if commit contains a local branch - check out the branch
if commit contains a remote branch which has a tracking reference - check out the corresponding local branch
if commit contains a remote branch without tracking reference - propose to create a tracking reference
otherwise check out the commit
The checkout commit option is available in the context menu.
