### ISSUE TITLE
1.0.69 loses tabs when you close Fork

### ISSUE THREAD

**Issue by clounie** [ForkIssues/Tracker#358]
Steps to reproduce:

1. Open Fork
2. Open a couple repositories
3. Cmd+Q to close Fork
4. Re-open Fork
5. ??? (all the tabs are gone)

---
Possibly related:

I also had some behavior for a bit which made Cmd+T (as well as its menu option) open a new window instead of a new tab...once I pressed the "+" button on the far right to open a tab, that seemed to fix the others' methods.  Perhaps an initial-install issue.

**Comment by DanPristupov** [comment]
Most probably you need to uncheck the 'Close windows when quitting' system option: https://user-images.githubusercontent.com/618115/42635895-94e9fc00-85e7-11e8-9c14-1ad63d16fbbd.png

**Comment by homm** [comment]
It looks interesting )

![close windows](https://user-images.githubusercontent.com/128982/43047810-ea1f56b0-8de5-11e8-8010-d6090a46610b.gif)

**Comment by DanPristupov** [comment]
Yesterday I released 1.0.69.3 which overrides the system settings and always restore the last session, so users don't need to change anything. It should make everybody's life better.

P.S. The problem is, I was sure that system settings is disabled by default. It was like that, but Apple has changed the default behavior few years ago.

**Comment by clounie** [comment]
Awesome - thanks Dan!
