### ISSUE TITLE
Custom external merge and diff tools

### ISSUE THREAD

**Issue by edwinm** [ForkIssues/Tracker#405]
I use the merge/diff tool of IntelliJ IDEA/PHPStorm/Webstorm because it has very good inline error reporting. That's because these IDE's have knowledge of the whole code base.

The merge and diff tool can be called from the command line, but I can't use it in Fork.

Maybe adding all IDE's of IntelliJ might be too much, but at least provide an option to enter a custom executable as merge and diff tool. Just like Custom Actions, but with the file paths as arguments.

Reference:
[Running IntelliJ IDEA as a Diff or Merge Command Line Tool](https://www.jetbrains.com/help/idea/2017.3/running-intellij-idea-as-a-diff-or-merge-command-line-tool.html)

**Comment by YesThatAllen** [comment]
This ties back to an early request I'd posted in an email. (thanks for the great support there too)

I'd love to send files to BBEdit for diff compare (despite the lack of 3 way view you mentioned..)

```
bbdiff [ --<options> ] [ NEWFILE OLDFILE  ]
```

**Comment by kervich** [comment]
I guess this comes down to supporting `[mergetool "yourFavouriteExternalTool"]` sections from your `gitconfig` (plus FileMerge or whatever comes preinstalled with macOS/Xcode) - adding support for more external diff/merge tools in Fork will result in chaos.

**Comment by jjrscott** [comment]
@kervich This is exactly the feature I'd like to have. At least listing the contents of `.gitconfig` below a devisor would be sufficient.

**Comment by tjluoma** [comment]
+1 for supporting BBEdit as a diff tool

**Comment by websolutions-hamburg** [comment]
![image](https://user-images.githubusercontent.com/26099903/78112993-5352a000-73ff-11ea-8aaa-fc6e66914abf.png)

Is it not possible to have the same custom options like the Windows version?

**Comment by geordiemhall** [comment]
+1 for being able to set up custom external mergers in the Mac version too (I use it them in the Windows version of Fork quite a lot).

For Unity it's useful to be able to resolve conflicts in YAML assets using the [Unity-provided merge tool](https://docs.unity3d.com/Manual/SmartMerge.html), but since it's bundled within the app folder the path is different per platform and per engine version. And since only certain assets need to be YAML merged (C# scripts and shaders can be text-merged like normal), being able to just click "Merge in external merger" in Fork on a per conflict basis was great. Edit: Looks like maybe it's now installed centrally after all?

Is the current list of External Merge tools based on a scheme that apps need to register for? If so I wonder if I could maybe make a Mac wrapper app for the tool instead..

**Comment by vgf89** [comment]
It would be nice to be able to save multiple custom presets and easily change merge tools while resolving conflicts. The Custom merge tool settings, as well as merger path for UnityYAMLMerge, get lost when switching merge tools.
