### ISSUE TITLE
Put "merge branch in to head" back in the main context menu?

### ISSUE THREAD

**Issue by YesThatAllen** [ForkIssues/Tracker#407]
One of the tasks I perform many times per day is to merge a branch in to my working copy's head.

As of Fork 1.0.7.0, this option is in a submenu, making it much harder to use.

I'd like to see that menu option put back in the main context menu.

![2018-09-18_11-20-56](https://user-images.githubusercontent.com/2879972/45701529-1aace780-bb35-11e8-829f-a1cb3015e12d.png)

Thank you!!

**Comment by DanPristupov** [comment]
Thank you for starting this topic. That is the thing I'd like to discuss.

The branch context menu structure **had** to be reworked. It was already too messy and I also could not add more items/features. That change was made to allow us to move forward.


I agree, that having "Merge" in the submenu feels a bit confusing. At least now, when everybody got used to a different location. But try to think like that: I move Merge to the root and next day somebody will ask to move "Checkout" there too. And it also will make sense, because Checkout is also being used very often. I move it to the root too and we end up with even bigger mess that we had initially.

On the other hand Checkout can be done by double-click and don't need a quick access menu item. May be we need to allow to merge by drag and drop the branch label instead?

I feel that calling merge takes a bit more time, but I don't see how to improve that. 

Any other opinions are very welcome.

P.S. May be we just need to get used to new menu?

**Comment by YesThatAllen** [comment]
Thanks Dan!

I don't think it's confusing, I think it's slow. As a comparison, I did not update Fork on my laptop.. having the Merge in the main menu is so much faster. 

Yes, I would expect that double-clicking a branch to offer it for checkout.

Here's a thought.. maybe each branch name could have [checkout][merge][delete] action buttons?

**Comment by DanPristupov** [comment]
> Rebase and Reset are still top-level items (and they should be!).
Rebase and Reset are top-level because they are related to revision, not to a branch.

What if we show a separate branch context menu when user clicks on branch label?

**Comment by YesThatAllen** [comment]
> What if we show a separate branch context menu when user clicks on branch label?

I had the same idea… seems like a nice compromise.

**Comment by gkopff** [comment]
(As an aside, I wanted to publicly say I love Fork!)

**Comment by DanPristupov** [comment]
I actually came here to say that I hear you guys and I fix the problem in the next update.

@gkopff thank you 🙂

**Comment by DanPristupov** [comment]
Aaand it's back! :)
