### ISSUE TITLE
Quick Push still displays confirmation dialog

### ISSUE THREAD

**Issue by pazner** [ForkIssues/Tracker#414]
When using the "Quick Push" command (either from the "Repository" menu or using the keyboard shortcut), the confirmation dialog still appears as if the "Push..." command had been used instead.

**Comment by DanPristupov** [comment]
Actually I was sure nobody uses quick push and I wanted to remove it.
Didn't know it's broken thought. Do you really miss it?

**Comment by will-e-p** [comment]
Well, I notice that when doing a commit and holding option, (so the button is now "Commit and Push"), it does a quick push. I use that quite often.

Sometimes I forget to do "Commit and Push" so then a quick push would be more convenient. (It seems inconsistent that one would be able to do a quick push only when also making a new commit).

May I also suggest Command-Option-Return as a shortcut for "Commit and Push" since Command-Return performs "Commit" and holding option changes the button?
