### ISSUE TITLE
Feature Request: Configurable Font / Monospace Font for Sidebar/branch/tags list

### ISSUE THREAD

**Issue by fbartho** [ForkIssues/Tracker#46]
I have a series of related branches that differ only in a number of the same digit width. These branches look out of alignment with a proportional width font there!

I'd be happy with a setting in settings, but I'm comfortable if it was a plist/json/config file I'd have to change, too!

**Comment by DanPristupov** [comment]
Hi @fbartho,

I want Fork to look like nicely in macOS UI environment and I'm trying to follow Human Interface Guidelines as much is possible.

Monospaced font most certainly can’t be applied to sidebar because it opposes UI design Apple rules in OS X. The monospace font must be used only to show documents or source code (proof https://developer.apple.com/macos/human-interface-guidelines/visual-design/typography/).

Also no Apple applications use fixed-width font on sidebar. Here's Finder, for example:
![2017-06-19 at 11 10](https://user-images.githubusercontent.com/618115/27277858-f7621eb0-54df-11e7-9175-2836024a3ad6.png)

**Comment by aziz** [comment]
I want the same thing, but I understand that it should not be the default option. 
As @fbartho mentioned it doesn't event need to a UI settings. just give us a way to change the font to something else through a config file

**Comment by fbartho** [comment]
@DanPristupov I totally see your point, and respect you for sticking to the HIG!

I actually have some good news here: I just learned a bit ago that there exists an attribute you can apply to fonts to allow proportional width, but also have fixed layout for the numbers in a string. I think it's a numeric attribute used for spreadsheets. I'll look it up and get back to this thread.

**Comment by fbartho** [comment]
https://useyourloaf.com/blog/ios-9-proportional-numbers/

It's a font feature! - I'm pretty sure it should be available on mac, but don't have a direct link for it at this time!

**Comment by DanPristupov** [comment]
Hey guys.

It looks like macOS supports `kNumberSpacingType`, `kMonospacedNumbersSelector` selectors. 👍

I'm going to investigate that approach and tell you about results during this week.

Please remind me if I forget about this.

**Comment by DanPristupov** [comment]
@fbartho @aziz thank you for bringing my attention to this. The digits on the sidebar look amazingly sharp and clear.

<img width="632" alt="2017-06-23 at 09 41" src="https://user-images.githubusercontent.com/618115/27471592-888028b8-57f8-11e7-909c-b9a067094025.png">

**Comment by aziz** [comment]
Now you can apply this to other parts of UI where a fixed width font makes more sense

- `sha`  column in the commit history and rebase window
- `time stamp` column in the commit history and rebase window

**Comment by fbartho** [comment]
That's great!!

**Comment by DanPristupov** [comment]
Just released 1.0.50 which uses monospace number font for sidebar and revision list.
