### ISSUE TITLE
Retry git commands?

### ISSUE THREAD

**Issue by otto-md** [ForkIssues/Tracker#505]
Since Sublime Text added minimal git integration I've started getting these errors pretty frequently:

<img width="680" alt="screenshot 2019-01-18 at 12 54 30" src="https://user-images.githubusercontent.com/31409359/51437452-e857f600-1c9e-11e9-90e1-094445affaba.png">

Thought the actions always seem to work the second time I try them. Perhaps Fork could retry these commands by itself before it showed an error message?

**Comment by DanPristupov** [comment]
I think retry button is not a solution.

Repository gets locked when something is being written to it. I'd rather investigate what is the requirement to **write** to repository so frequently? Both XCode and Visual Studio have git integration but don't lock the repo.

I suppose it could be caused by `git status` request. There's a section in git docs on how to use it properly.
https://git-scm.com/docs/git-status#_background_refresh

> When status is run in the background, the lock held during the write may conflict with other simultaneous processes, causing them to fail. Scripts running status in the background should consider using git --no-optional-locks status

**Comment by DanPristupov** [comment]
@otto-md yes, you should know their point of view as well
