### ISSUE TITLE
[Feature Request] Filter current branch, whichever it is

### ISSUE THREAD

**Issue by stk-ableton** [ForkIssues/Tracker#520]
I like the ability to set a filter for one or more branches (see #289), but I'd like to have an easier way to automatically filter the currently checked out branch. That's almost always the default view I want to see, and currently it's cumbersome to do, e.g. after checking out a different branch in the terminal. I then have to go find the previous branch in the list, unfilter it, and find the new branch (that's easier because it's bold) and filter it. I would like to not have to do any of these steps, and have the list of commits update automatically for the new branch.

One way to add that feature might be to add the special HEAD branch to the list not only when on a detached head, but always, and allow setting a filter on that as well.

**Comment by DanPristupov** [comment]
> I'd like to have an easier way to automatically filter the currently checked out branch

I agree. Let's discuss, how we can improve the filter.

> One way to add that feature might be to add the special HEAD branch to the list not only when on a detached head, but always, and allow setting a filter on that as well.

I suppose this can be a bit confusing way to filter current **branch**, especially for new users, because HEAD means active commit.

What if we make the active branch to be always first on the sidebar? In this way it will be always easy accessible.

> after checking out a different branch in the terminal. I then have to go find the previous branch in the list, unfilter it, and find the new branch (that's easier because it's bold) and filter it

In the latest Fork update (1.0.73) I introduced the filter panel above the revision list, which allows to reset filter in one click. If we make the active branch to be first on the sidebar, filter switching will require two clicks.

> That's almost always the default view I want to see, and currently it's cumbersome to do, e.g. after checking out a different branch in the terminal.

We can automatically switch active filter on branch checkout in Fork (I know, you mentioned terminal, so consider this as small improvement).

I will think about that more during the day. Any other ideas and opinions are welcome 👍.

**Comment by maksimovic** [comment]
> What if we make the active branch to be always first on the sidebar? In this way it will be always easy accessible.

If I understood this correctly - that would mean that the active branch would go up and down the tree whenever one is switched to. Doesn't sound like a nice to have feature to me 🤔

**Comment by DanPristupov** [comment]
We can change the funnel-button behavior to not `add` but `replace` (similar to usual selection). The multi-filter will be available as 'option-click' (that behavior will be described in tooltip). In this way we will be able to move filter in one click.

@maksimovic 
We can show filter icon near the active branch on status control (when mouse over ?).
![filter](https://user-images.githubusercontent.com/618115/52700946-5ed3d500-2f79-11e9-97cf-0ace85732816.png)

**Comment by DanPristupov** [comment]
@maksimovic
> that would mean that the active branch would go up and down the tree whenever one is switched to. Doesn't sound like a nice to have feature to me

I see now. It's not a good idea for repos with thousands branches.

**Comment by stk-ableton** [comment]
>> One way to add that feature might be to add the special HEAD branch to the list not only when on a detached head, but always, and allow setting a filter on that as well.

> I suppose this can be a bit confusing way to filter current **branch**, especially for new users, because HEAD means active commit.

Exactly, that's almost always what I want; I don't really see what's confusing about it.

For the record, this is the behavior you get when you start `gitk` without parameters, or when you type `git log` without parameters in the terminal, for that matter.

The only situation I can think of where this might not be what you want is when stopping in the middle of an interactive rebase. It would then only show commits from the current commit downwards, instead of all commits on the branch. However, the current behavior is not ideal either; it continues to show the unrebased branch, and not any commits you made or amended during the rebase. Ideally I want see both the branch and HEAD in this case; not sure how to best do this.

> We can change the funnel-button behavior to not 'add' but 'replace' the filter

That would help a bit for me, I think. It's very rare that I want to filter more than one branch at a time.

I think putting the current branch at the top of the list would also be something that I would like. I don't think it would be a problem for me that it jumps in the list when I check out another one. Maybe this could be an option in preferences?

**Comment by DanPristupov** [comment]
Regarding putting the active branch on the the list. I think I was too fast saying "It's not a good idea for repos with thousands branches". People should never have >100 **local** branches under normal circumstances.

@maksimovic could you elaborate your use case? How many local branches do you have usually? Do you use folders?

> I think putting the current branch at the top of the list would also be something that I would like. I don't think it would be a problem for me that it jumps in the list when I check out another one. Maybe this could be an option in preferences?

Yes, I think this is that rare case when we can add an option to preferences :).

**Comment by maksimovic** [comment]
> @maksimovic could you elaborate your use case? How many local branches do you have usually? Do you use folders?

At our main repo I often have 20+ local branches at any given time.

I do like using folder-like structure, but I avoid it in this particular huge repo because most of the other people don't use that, and they also never clean up branches in their forks, which leads to a high probability for conflicts when they checkout my branch-in-a-folder. E.g. it happens that most of the people have a `dmc` branch (inherited from the upstream or their own - it's an ongoing sub-project's codename), and they can't checkout my `dmc/554-fix-something` branch. But, I don't see how would that happen here anyway. I just don't like the idea of having to constantly chase branches around in the sidebar. Maybe it wouldn't be such a big deal, I just don't get how it would useful or more [user|brain]-friendly from my current POV.

To be honest, I also cannot see the reason to change any of the existing behaviors (e.g. funnel button to replace a filter instead of to add it) in order to cover 1 new specific scenario, which also happens when an action isn't even performed in Fork.

**Comment by DanPristupov** [comment]
@maksimovic thank you.

> To be honest, I also cannot see the reason to change any of the existing behaviors (e.g. funnel button to replace a filter instead of to add it) in order to cover 1 new specific scenario, which also happens when an action isn't even performed in Fork.

It's not about that particular scenario. I just think that switching filters takes too much efforts now, and I'm looking for a way to improve that.

The common workflow probably looks like this:
- checkout `feature1`, set filter on `feature1`.

then we need to start working on `feature2`
- checkout `feature2`
- find `feature1` on the sidebar, remove filter. You need to remember what branch you was working on previously or look through all branches. It becomes more complicated if you used multi-filter.
- find `feature2` on the sidebar, set filter

Showing the active branch at the top should make it easy accessible. In this way setting filter on the active branch will always take O(1) time.

**Comment by maksimovic** [comment]
I don't know - I'm not strictly against it, except that what I imagine with a pinned active branch to the top isn't what I'd usually expect :D

I also don't use filtering feature, searching for a branch and checking it out is pretty much the most advanced thing I do in the sidebar as far as filtering goes.

I'm just a regular user that will keep using Fork anyway because its benefits are far better than any other existing tool's ones.

**Comment by stk-ableton** [comment]
Just to reinforce my point: For me, pinning the active branch to the top is only a crutch. Yes, it would allow me to click the filter button more easily, but ideally I want to not have to do that at all, and have the filtering be fully automatic.

If I can't have the fully automatic version, then at least pinning the active branch to the top is better than nothing. 😄  

(No new information here, just saying it again because I think the discussion slightly went away from the original request.)

**Comment by DanPristupov** [comment]
Thank you very much. I understood your requirements. This is a new info for me and I need to figure out. I think we need to move toward automatic behavior.

As for now I will proceed with moving the active branch to the top. We'll see how it works out.

**Comment by DanPristupov** [comment]
Alright, 1.0.74 is out.

**Comment by stk-ableton** [comment]
Awesome, 1.0.74 is a big improvement for me. I only just realized that it also includes the exclusive filtering by default (clicking a filter disables any other filters; command-click adds a filter). The release notes don't mention this.

**Comment by DanPristupov** [comment]
Great!

> The release notes don't mention this.

I mentioned that not clear enough probably:
> Improved filter behavior. Use ⌘-click for multi-filter

**Comment by stk-ableton** [comment]
I'm confused, which release notes are you talking about? The ones at https://forkapp.io/releasenotes don't mention this at all.

**Comment by DanPristupov** [comment]
The ones Fork shows in the automatic update dialog (can't show a screenshot, because I've already updated to 1.0.74).

Sometimes I add additional information to the update dialog.

I didn't expect this to end up being confusing, to be honest. Sorry about that.

**Comment by DanPristupov** [comment]
What do you think about the idea to detect if current branch has changed and switch the filter correspondingly (only when filter == current branch)?

For example:

* active branch - `master`, filter - `master`. Checkout `develop` will switch filter to `develop`.
* active branch - `feature1`, filter - `master`. Checkout `feature2` will NOT change filter (because filter != active branch).
* active branch - `master`, filter - `master`. Checkout from CLI will also switch filter to `develop`.

**Comment by stk-ableton** [comment]
Yes, I think this would definitely be an improvement over the current behavior for me.

**Comment by DanPristupov** [comment]
Fork 1.0.75 just came out. It switches the filter automatically in the way I described in the previous message.

**Comment by stk-ableton** [comment]
This is great, it's a big improvement. After working with it for a while, I find that this almost always behaves the way I want.

The one big problem I still have with this is when going to a detached head; in that case the filter turns off entirely. This is very annoying. The most common situation where this happens is when stopping in the middle of an interactive rebase.

To improve this, I'd suggest to keep the filter when going from an active branch that is filtered to a detached head. This is not the ideal behavior that I would wish for, because ideally I would want to see both the previous active branch and the detached head, but that seems a lot harder to do.

**Comment by DanPristupov** [comment]
> To improve this, I'd suggest to keep the filter when going from an active branch that is filtered to a detached head.

There's a problem with Interactive rebase. Preserving the filter will make the rebased commits hidden (i.e. the ones which belong to the detached HEAD).

We can do the following:
- Do not reset filter on transition from active branch -> detached head (as you proposed)
- When filter is on and detached HEAD, then add HEAD commits to the commit list.

Basically, always show HEAD commits in detached HEAD, even if filter is on.

What do you think? Could that work? Will it introduce any other problem?

**Comment by stk-ableton** [comment]
> Basically, always show HEAD commits in detached HEAD, even if filter is on.

Yes, this would work for me. I didn't realize that you could just do this implicitly. Seems perfect to me.

**Comment by stk-ableton** [comment]
The new logic in 1.0.80 is fantastic. Thanks! Huge improvement.

**Comment by DanPristupov** [comment]
We have discussed how to switch the active filter on checkout, but missed the original request:

> I'd like to have an easier way to automatically filter the currently checked out branch.

In Fork 1.0.82 I added an option to toggle the active branch filter.

<img width="461" alt="Screenshot 2019-07-22 at 12 02 53" src="https://user-images.githubusercontent.com/618115/61624309-a709c880-ac78-11e9-93b6-aac5df9dfaed.png">

You can also use the Ctrl+Shift+A keyboard shortcut.

**Comment by DanPristupov** [comment]
There's a regression in 1.0.86 which breaks the automatic filter switch. It will be fixed in 1.0.87.
