### ISSUE TITLE
Use force-with-lease at force push

### ISSUE THREAD

**Issue by DaSchTour** [ForkIssues/Tracker#526]
I would suggest that the force push option should be "defused" a bit like described in https://developer.atlassian.com/blog/2015/04/force-with-lease/

I think it would be great if a force push would first try to push with `--force-with-lease` and if this fails give the user options to make a `pull --rebase` or a hard `push --force`. This would be a great feature and improve working with workflows were branches are rebased and force push is needed while avoiding unwanted loss of commits when working on bigger teams.

**Comment by DanPristupov** [comment]
Push is always --force-with-lease.
<img width="502" alt="screenshot 2019-02-15 at 08 46 53" src="https://user-images.githubusercontent.com/618115/52842085-3fb28000-30fe-11e9-8008-3dfcaf730ad2.png">

Implementing custom behavior for --force-with-lease isn't worth the time, because it happens quite rarely.

**Comment by DaSchTour** [comment]
Okay, well. Didn't know that :sweat_smile:
Great, thanks :+1:
