### ISSUE TITLE
Stage selected lines (and files) via pressing Enter

### ISSUE THREAD

**Issue by herrherrmann** [ForkIssues/Tracker#54]
Hello Dan,

thanks for the great app. I love selecting single lines and blocks of code in Fork's code inspector and staging them individually. I kinda expected that pressing spacebar would also work in order to add the current selection to the staged files (just like when selecting files in the file tree/list).

So maybe this is a quick thing to add that would definitely boost my workflow and also be an intuitive feature in general?

**Comment by DanPristupov** [comment]
Hi Sebastian,

I have some bad news. I'm going to stop using spacebar as a hotkey for toggling stage/unstage in the next Fork release. But I promise there will be a better feature which uses it :). I'll give more information tomorrow.

However, I'd like to keep the toggle feature and looking for an alternative hotkey for it.
Just thinking out loudly:
- Use enter key instead of space bar.
- Finder uses Cmd+Up,Cmd+Down for going to the upper level or deeper. We can user Cmd+Down as stage, Cmd+Up as unstage.

The shortcut will work for both files and text selection. Do you think Enter could be a decent replacement?

**Comment by DanPristupov** [comment]
Starting from 1.0.50 I use spacebar for toggling Side-By-Side view, which works similar to QuickLook in Finder (which also uses spacebar).
![2017-06-30 at 16 33](https://user-images.githubusercontent.com/618115/27740329-febb909e-5db1-11e7-96ec-9ac132ee23f4.gif)

**Comment by clounie** [comment]
For something like Stage/Unstage, you want to be able to have one hand on the keyboard and one on the mouse - otherwise why have a keyboard shortcut when the button is so close?

I really like the idea of a one-button hotkey to stage/unstage selected. Have never used a client that had that, but it'd be a *lot* faster when I'm going through large files.

**Comment by DanPristupov** [comment]
I also prefer one hand on the keyboard and one on the mouse pattern. And that's why `Cmd+Shift+S` for stage works well for me. It's easy enough to press it, but at the same time protects you from staging something unintentionally.

**Comment by herrherrmann** [comment]
I see! Really like the new "quick look" into diffs. :)
Using `cmd+shift+s` for staging and especially `cmd+shift+u` for unstaging is a bit cumbersome for me (pressing `cmd+shift+u` isn't really possible with one hand, at least not for me :P). I guess I'd really welcome the usage of `Enter` to stage/unstage files and lines!

**Comment by DanPristupov** [comment]
Actually, do we really need `Cmd+Shift+U`? I can use `Cmd+Shift+S` for both staging and unstaging (and also keep `Cmd+Shift+U` for backward compatibility with people who got used to it :)).

I'm going to handle `Enter` as shortcut in next update.

**Comment by herrherrmann** [comment]
1. You're right, I'd also expect `cmd+shift+s` to unstage changes when I'm acting in the list of staged changes.
2. Yippie, thanks!
Will use the quick look feature more often now that it's there and I will let you know if anything's off with it for me!

**Comment by clounie** [comment]
Definitely like the Cmd+Shift+S for unstage as well - I naturally tried to do that without even thinking about it.

**Comment by DanPristupov** [comment]
@clounie My left hand is always on the left area and Cmd+Shift+S fits perfectly for me.
So, answering your question, I will keep both old and new shortcuts.

Summarizing:
- Stage/Unstage: `Cmd+Shift+S` or `Enter`
- Unstage: `Cmd+Shift+U` (for backward compatibility)
- Discard: `Cmd+Shift+D` or `Backspace`

**Comment by DanPristupov** [comment]
@everyone please check the `1.0.51` Fork update.

**Comment by herrherrmann** [comment]
Amazing, thanks for the quick and sane change!
