### ISSUE TITLE
Bug in recent changes to branch sort order sorts folders first

### ISSUE THREAD

**Issue by marcomasser** [ForkIssues/Tracker#560]
A recent release brought changes to the sort order of branches, but it seems like the sort order of “folders” are broken now. It looks like this for me:

<img width="219" alt="branch sort order" src="https://user-images.githubusercontent.com/624299/53791091-d79ad100-3f28-11e9-9296-60611eb1a7d5.png">

Before those recent changes, “personal” was listed at the bottom, where I would expect it to be.

**Comment by DanPristupov** [comment]
It might be that the new order was not applied to all the tabs. Did you try to restart the application?

**Comment by marcomasser** [comment]
Yes, I see this sort order for a while now, across multiple restarts of Fork.

**Comment by DanPristupov** [comment]
Ouch, sorry. I just noticed that you mentioned the folders. I somehow missed that.

It's not a bug, but a feature. Folders are always sorted first now.

**Comment by marcomasser** [comment]
> Folders are always sorted first now.

Oh no, please don’t do that without making it an option. I assume there are good reasons why this is a common thing but I really, really don’t like this and I suspect I’m not the only one.

Having the master branch at the top is useful. This kind of sort order breaks that.

**Comment by maksimovic** [comment]
My opinion on this, if I could pick my poison:

- master on top is handy, but it's fine being at its own position based on the name
- I'd prefer folders to be sorted just as regular branches are, not forced to either top or bottom, so like this:

```
- branch-1
- branch-xyz
- folder
|-- branch-1
|-- branch-xyz
- tests
|-- a1
|-- a2
- xxx-hidden-porn-branch
```

**Comment by DanPristupov** [comment]
OK, I'll think about removing that feature.

It's really difficult to change something when people got used to it.

**Comment by marcomasser** [comment]
Glad to hear it! Thank you for being so responsive, BTW.

And yes, it is always difficult to take something away or change something users expect to work in a certain way. But I think in this case, a setting wouldn’t be too bad to make it a user preference since you already have a menu that is shown on right-click that contains similar settings. The harder question is maybe: What should the default be 😉

**Comment by maksimovic** [comment]
People resist changes, no matter how good or bad they are 🙈 

Speaking of defaults... I think that majority of Fork users who used a GUI before - used SourceTree, but switched (myself included) due to SourceTree deteriorating in various areas. Probably there are no stats available unless Fork's customer base is surveyed, except proofs in issues here that result from SourceTree messing with git or similar ones. Maybe the best bet would be to keep sorting as it is in SourceTree? 🤔 

I'm a great "Settings" fan, although I know that offering too many options to customers isn't always the best idea, for various reasons. However, _maybe_ Fork could offer a couple of sorting options:

- `master` on top: y/n
- folders: default/top/bottom
