### ISSUE TITLE
Extra empty parameter passed to custom action

### ISSUE THREAD

**Issue by stk-ableton** [ForkIssues/Tracker#574]
When you install a custom action and leave the "Parameters" field empty, an extra, empty parameter will be passed to the script. This is a problem in cases where the script is picky about what parameters are passed to it, and errors out for any that it doesn't recognize.

There are other problems with parameters, but I suppose they are less important in practice. For example, if you enter `" "` in the "Parameters" field, expecting this to pass a single space to the script, it will instead pass `"` and `"` as two arguments. Not a problem for me personally, just pointing it out.

An easy way to experiment with this is to create a script with this content:
```
#!/usr/bin/env python
import sys
print sys.argv
```
and then configure various parameters for it.

**Comment by DanPristupov** [comment]
Custom action process gets an optional array of string arguments. I just split the user arguments string (`arguments = argumentsString.split(" ")`) and pass the result array to the process.

> When you install a custom action and leave the "Parameters" field empty, an extra, empty parameter will be passed to the script.

This one is easy. When the given string is empty, I must pass **no** arguments (`null`), instead of array with a single empty string. I'll fix this right now and it will be a part of the tomorrows update.


> if you enter " " in the "Parameters" field ... it will instead pass " and " as two arguments

This one is more difficult. Looks like using `split` isn't really correct in that case and I need to implement a simple tokenizer. I'll leave it as it is, until there's a real reason (request) for that.

**Comment by DanPristupov** [comment]
Fixed in 1.0.75
