### ISSUE TITLE
Can see only personal project for Bitbucket account

### ISSUE THREAD

**Issue by mskonovalov** [ForkIssues/Tracker#619]
For GH account I see (in clone window) all the repos personal and from all of the orgs.
But fot Bitbucket I can see only personal projects and no from org.

**Comment by DanPristupov** [comment]
I suppose this feature will not appear in the near future.

Currently there's no way to fetch this info in BitBucket API 2.0. Bitbucket support proposes to use the 1.0 API which has been deprecated for more than a year (!) and had to be removed April 29th, 2019 (!!), but apparently is still active. You can read some info there: https://community.atlassian.com/t5/Bitbucket-questions/Bitbucket-API-get-update-all-users-with-access-to-repository/qaq-p/1153453.

SourceTree itself uses both 2.0 and 1.0 APIs, but I don't want to step into this mess. I'd rather spend my time making Fork better.

**Comment by andrews05** [comment]
Is this not the correct endpoint?
https://developer.atlassian.com/bitbucket/api/2/reference/resource/user/permissions/repositories

**Comment by saisuryakat** [comment]
@DanPristupov I think this can be achieved through Bitbucket APIs 2.0, but instead of 1 step, you need to do in 2 steps

1.  Invoke Projects endpoint with access_token and role=member
```GET https://api.bitbucket.org/2.0/teams?access_token=<access_token>&role=member```
This will list the projects and their usernames in which the user is a member
Sample JSON:
![image](https://user-images.githubusercontent.com/62474785/83607227-0af16300-a5a5-11ea-9109-2e5169033ea3.png)

2. Invoke Repositories endpoint with same access_token and username(user and team separately )
```GET https://bitbucket.org/!api/2.0/repositories/<username>/?access_token=<access_token>```

This will list all repositories belonging to that _username_

I have submitted detailed feedback from Fork App once, but didn't receive any reply for that.

**References**

* https://developer.atlassian.com/bitbucket/api/2/reference/resource/teams/%7Busername%7D/projects
* https://developer.atlassian.com/bitbucket/api/2/reference/resource/teams/%7Busername%7D/repositories

**Comment by DanPristupov** [comment]
@saisuryakat thank you. I will try that.

**Comment by DanPristupov** [comment]
@saisuryakat it works but it still doesn't show all repos the user has access to (for example shared repos).
Anyway, showing the groups' repos will be a good improvement. I just need to find a way to fit that multi-request approach nicely :)

**Comment by saisuryakat** [comment]
@DanPristupov Glad to know it worked for teams' repositories, I haven't worked with shared repositories, but one humble suggestion is to follow how the bitbucket.org works, We've learned about the APIs' usage from Chrome's Developer Tools, if shared repos are listed in bitbucket.org then it can be achievable with rest apis(again our personal experience), the documentation is very poor, developer tools on bitbucket.org is far better

**Comment by lksoft** [comment]
@DanPristupov 
Spelunking a bit for the bitbucket.org website, I found these 2 API endpoints that *should* be able to get what you need:

1. List workspaces for the user: https://bitbucket.org/!api/2.0/workspaces?q=name~%22%22
2. Then using the uuid (where indicated below without the curly braces returned in the JSON - they are in the percent encoding already) returned from that, this endpoint gets repos: https://bitbucket.org/!api/internal/dashboard/repositories?pagelen=25&page=1&q=workspace.uuid%20%3D%20%22%7B[UUID_HERE]%7D%22

Hope that is helpful!

Thanks,
Scott

**Comment by DanPristupov** [comment]
@lksoft 
> Hope that is helpful!

It is! Thank you very much 👍 I'm curious how long this will stay open, but it works now 🙂

The fix is available in Fork 1.0.97.

**Comment by lksoft** [comment]
Awesome. Glad I could help. I hope that it stays open as well. It is much more useful now when cloning ;-)

Scott

‌Little Known Software
‌scott@littleknownsoftware.com‌
—
“Perfection is achieved,
not when there is nothing more to add,
but when there is nothing left to take away.” – Antoine de Saint Exupéry 
—
Mac Mail Users: check out our site <http://smallcubed.com/> for great Mail plugins!
—
‌
‌
