### ISSUE TITLE
Application Size

### ISSUE THREAD

**Issue by ennalax** [ForkIssues/Tracker#69]
Among other things - one of the benefits was it's size.  
1.0.52.1 added a bundled git in the application and this changed the app size from ~38MB to ~124MB.  Is it possible to make this a downloadable asset? This way Xcode users won't get yet another git instance on their machines...

**Comment by DanPristupov** [comment]
Hi,

I also do not like that Fork tripled it's size. Here's the explanation why I did this:

There are many issues with the default Apple Git instance:
- Apple made impossible to use some important git features (for example custom GIT_ASKPASS, which is ignored).
- People without git must install XCode in order to use it (https://github.com/ForkIssues/Tracker/issues/38). And it requires gigabytes (!) of data.
- Apple Git has bugs: https://twitter.com/CJFWeatherhead/status/868602376462233600
- Once Apple blocked access to whole git until user opens XCode and confirms EULA (this happened after XCode 8 update a year ago).

Yes, I can allow to use a brew git instance. But,
- There's no way to check if Apple Git is installed without prompting the 'Install XCode' dialog. It shows  automaticaly (!) on accessing /usr/bin/git. So I can't handle the absence of git and show some "find git location dialog", without asking user to install XCode.
- Implementing the downloader also requires much time.

And the main problem.

I spend about 10-15% of my time solving problems caused by shared git instance.
- some people install some cool git extensions, custom configs, whatever
- sometimes other software leave garbage in global git config, which exists even after uninstall (hi mergers!)
- sometimes people change some global git variables and don't remember about it (stackoverflow?)
- most of these emails start with a 'The latest Fork release doesn't work' subject. I can't ignore emails with such titles, right? After few hours of investigation it usually turns out that 'Oh, I forgot that I installed xx'.

Bundled git solves all these problems.

So, the main reason why I bundled Git is because I have limited resources and I want to dedicate my time to new features and REAL bugs, not users' problems.

**Comment by aziz** [comment]
Thanks for shedding some lights on this. It all makes sense now. I didn't like this but reading all the issues you mentioned, I agree that it is the best solution.

**Comment by ennalax** [comment]
I understand the implications fully and I appreciate the time you took to answer. It all makes sense now.

On a side note - by adding a downloader I did not mean anything fancy - I meant on first start running a script that checks "which git" to see if a suitable git version is available and if this is supported by the app and if not using curl to pull a version from server

``` bash
installed_git_path=which git
installed_git_version=git --version  # process if you need a certain version
app_support_path=~/Library/Application\ Support/Fork
if !installed_git_path then
  curl -o $(app_support_path)/local_git.tar.bz2 https://github.com/Fork/current_local_git.tar.bz2
  tar xjf $(app_support_path)/local_git.tar.bz2
  rm -f $(app_support_path)/local_git.tar.bz2
fi
```

**Comment by DanPristupov** [comment]
@ennalax thank you for the script. I didn't know it can be done so easy 👍 .

However there are also many potential problems:
- show progress, handle connect interruptions and bad speed, handle updates
- security issues. Remember that git has access to private source code. So, the installer have to ensure that the git archive has not been modified by somebody else. The archive must be signed by a revokable certificate which tied to the hardware of the build system.
- etc

Again, this could be possible if Fork was owned by a huge corporation. But there's only my wife and I.
