### ISSUE TITLE
Interactive rebase

### ISSUE THREAD

**Issue by DanPristupov** [ForkIssues/Tracker#7]
Interactive rebase allows you to change a sequence of your commits. You can reorder, split, squash and edit your commits.

Please upvote if you miss it.

**Comment by jbergstroem** [comment]
I think this is a great feature. The number one reason for me using Fork over command-line is just how quickly it is to shuffle and navigate commits (especially partial staging). This is exactly what you do in an interactive rebase, which would make it even more useful for me.

**Comment by aziz** [comment]
This is the missing feature in all git gui apps. 
Please make it happen

**Comment by DanPristupov** [comment]
It takes much time to design and implement such a big and complex feature properly :).

I'm proud to say that we just released Fork 1.0.46 with the Interactive Rebase.

Few notes:
- We spent a lot of time testing it. But still, please create backup tags (there's a special checkbox for that)!
- Use drag'n'drop to reorder commits.

I would really appreciate any feedback.

![2017-05-19 at 16 28](https://cloud.githubusercontent.com/assets/618115/26252531/bc48f336-3cb0-11e7-9456-3c8267598898.jpeg)

**Comment by aziz** [comment]
Thanks for making this happen. It is awesome.
Here are some feedback:

1. I don't like that it runs in a modal that blocks the rest of the UI. It would be great if it opens in a new window that I can put side by side so that if I need to check something on the repo I can still work with the app. 

2. When a rebase is in progress the app shows a warning message on the top (this could be more visible by changing the background color to a light yellow to differentiate it from the rest of UI.
Additionally if a rebase is in progress and you try to start a new rebase the modal flashes for a fraction of a second that might give an impression that something went wrong. the flashing of the modal should be prevented.

3. There are some small UI glitches that hopefully will get fixes soon
<img width="117" alt="screen shot 2017-05-20 at 9 12 31 am" src="https://cloud.githubusercontent.com/assets/3202/26273941/8978e646-3d3c-11e7-8854-96b1bf3de379.png">
<img width="207" alt="screen shot 2017-05-20 at 9 12 15 am" src="https://cloud.githubusercontent.com/assets/3202/26273940/8976b100-3d3c-11e7-815b-e502385c6947.png">

**Comment by DanPristupov** [comment]
@aziz 

> I don't like that it runs in a modal that blocks the rest of the UI.
Interactive rebase moves the repository to a special rebase-in-progress state, which doesn't allow too much editing. Popup is a good way to bring user attention to rebase and prevent him from breaking something.

> When a rebase is in progress the app shows a warning message on the top (this could be more visible by changing the background color to a light yellow to differentiate it from the rest of UI.
I'll improve the visibility in the next version. I'm going to check how Apple shows such notifications.

> if a rebase is in progress and you try to start a new rebase the modal flashes for a fraction of a second that might give an impression that something went wrong. the flashing of the modal should be prevented.
Thanks, will fix this.

> There are some small UI glitches that hopefully will get fixes soon
Will fix this too.

Thank you for the feedback. I'm going to fix the issues and release an update this week.

**Comment by DanPristupov** [comment]
Just released 1.0.47. Many things have been improved. I also made rebase conflict resolution more fluent.
