### ISSUE TITLE
Why does Fork need access to my reminders?

### ISSUE THREAD

**Issue by Drarok** [ForkIssues/Tracker#708]
I've taken a look at Fork for the first time today, and on first launch I see the following:

![Screenshot 2019-08-15 at 16 05 46](https://user-images.githubusercontent.com/55830/63105048-ee356180-bf77-11e9-84aa-a50e66760a8c.png)

With a closed-source app, this doesn't inspire confidence…

I'm running macOS 10.15 Beta (19A526h).

**Comment by DanPristupov** [comment]
Because you selected user root as the default source folder.

**Comment by Drarok** [comment]
Well, I accepted the default which is user root, I didn't _select_ it.

That also doesn't really explain anything. Should the default be changed? Should Fork automatically ignore private things like Reminders and Photos?

**Comment by DanPristupov** [comment]
> Well, I accepted the default which is user root, I didn't select it.

Fork just scans git repos in the given folder. Starting from the 10.13 MacOS shows those dialogs automatically when any application touches some special folders.

> Should Fork automatically ignore private things like Reminders and Photos?

Most likely it shouldn't. Fork doesn't know anything about private folders. It simply goes through subfolders looking for `.git` directories.

> Should the default be changed?

I can change it if you suggest a better default value.

**Comment by tmdkamins** [comment]
5 years later, still an issue... There is a popup that looks kind of like a registration window (asks for name, email, and directory) but which is easily ignorable indefinitely and Fork works fine without it. I finally decided to fill it out because, even though I didn't know what it was for, I got tired of having it pop up. I just accepted the defaults. Suddenly over the next several seconds I get probably 5+ popups from MacOS asking for permission to access various folders, reminders, and more.

I understand the alleged intent is to scan for .git folders. I have zero desire for that to happen and will add repos I want Fork to manage. If anybody wants this magic, let them click a "Find Local Repos" button, and make it clear that Fork is going to scan their drive.

This is bad behavior, especially for a closed source app. The issue is not what the default value is. It's the assumption that everybody wants this kind of intrusive design in the first place. Consider that this is a turnoff for many power users who will decide the software is not trustworthy and simply move on without ever saying anything.

P.S. If you landed here via web search like I just did, know that Fork is *great* overall, my favorite git gui, and I have no reason not to trust it. But this issue is silly and easily fixed.
