### ISSUE TITLE
Logging into multiple GitHub accounts

### ISSUE THREAD

**Issue by jwknz** [ForkIssues/Tracker#766]
Hi,

Is there a point on the roadmap to provide the option to login with multiple accounts from the same provider?

I have a work and private GitHub account and would like to use both without explicitly having to logout and login every time.

If this can already be done and I have missed it, please let me know :-)

**Comment by mikerochip** [comment]
I'm not actually seeing a way to logout on mac. I haven't tried nuking credentials in keychain yet, but that must be the only option?

**Comment by Stanzilla** [comment]
Yeah I would really need this as well

**Comment by mikerochip** [comment]
FWIW this might not be straightforward for the Fork team just because of how git auth works with https. The best option I found was to just use ssh and set all that up outside of Fork, but once it's setup, you can use Fork with multiple repos on different accounts, no problem. I'm not a cmd line/ssh/mac power user, so this took me a massive amount of googling and stitching together stack overflow, stackexchange, and man pages to make it happen.

**Comment by Stanzilla** [comment]
signing out is only broken because it does not clear the cache. when you sign out and then press log in again, it tries to authenticate against the old account, disregarding which email you entered in the field

@mikerochip can you post a guide somewhere? kinda offtopic for this issue

**Comment by mikerochip** [comment]
Relevant for solving the OP's use case, but yes I agree there are bugs and it would be nicer in general to have a multi-account setup without having to leave the client.

This took longer than I'd like but here it is: https://medium.com/@mikerochip/my-multi-account-github-workflow-on-mac-133708a93544
