### ISSUE TITLE
High ports usage: possible memory leak

### ISSUE THREAD

**Issue by homm** [ForkIssues/Tracker#881]
After 8 days of working, Fork is the bigest ports consumer in the system.

<img width="741" alt="Screenshot 2020-01-22 at 15 02 25" src="https://user-images.githubusercontent.com/128982/72892841-9ec63f00-3d28-11ea-8600-12ebcf6115cf.png">

Memory usage is also constantly increasing. This could be related.

**Comment by DanPristupov** [comment]
Is that bad? Actually what are those ports? I couldn't find any info about that.

**Comment by homm** [comment]
This doesn't look natural. At least that could be not released resources that are responsible for memory growth.

**Comment by homm** [comment]
> Actually what are those ports?

Opened files, pipes, connections, I suppose.

**Comment by DanPristupov** [comment]
We only use pipes (but do that a lot). I'll try to check if I do everything correctly.

**Comment by akunzai** [comment]
Hi, @DanPristupov 

After opening a huge git repository, I noticed high memory usage, which might be related.

<img width="695" alt="Fork high memory usage" src="https://user-images.githubusercontent.com/574719/232666616-b8b2ca5e-2803-473e-976d-b5e8d336b0e6.png">

## Huge git repository

- https://github.com/apereo/cas
- https://github.com/microsoft/vscode

## Environment

- Fork version:  2.28.1
- macOS version: 13.3.1

**Comment by DanPristupov** [comment]
@akunzai the reason is the (currently) first commit in the Cas repository which is big (5.85Gb). The loading also takes 33 seconds:

```
$ time git show da5d70c | wc -m
 5853601458  <-- 5.85Gb
git show da5d70c  56.77s user 6.29s system 96% cpu 1:05.35 total
wc -m  33.40s user 2.24s system 54% cpu 1:05.35 total   <-- 33.4 seconds
```
Set 'hide' on `origin/gh-pages` and Fork will use ~400Mb.

**Comment by akunzai** [comment]
Hi @DanPristupov

Thanks, It works!

**Comment by homm** [comment]
Looking at the old screenshot I would say now memory consumption and ports number is a way smaller even after several days since launch.

**Comment by DanPristupov** [comment]
@homm regarding the issue with large open port number. I managed to reproduce the problem in just a few lines of code and contacted the Apple support with that. After the investigation, they answered that this is a bug with synchronization on process start in macOS and it will be fixed in next major update (which should have been macOS 11).

Since then I haven't debugged that problem again.

P.S. It's unrelated, but I also found a kind-of-similar bug in .Net and also reported it. Turned out the bug has been existing since Windows 9x (yes!) and now when .net became cross-platform .net-core, it also exists on MacOS and Linux. The developers told me that currently they don't have plans to change the behavior. Surprisingly starting an internal process is still a tricky task :)
