### ISSUE TITLE
Render markdown in repository preview

### ISSUE THREAD

**Issue by jbergstroem** [ForkIssues/Tracker#9]
<img width="1440" alt="screen shot 2017-04-18 at 3 31 18 pm" src="https://cloud.githubusercontent.com/assets/176984/25147137/d9c93ec4-244c-11e7-8f58-0d92aac512b1.png">

(right area in screenshot)

Rendering markdown in the "preview repo" screen would make the readme easier to read/identify!

**Comment by DanPristupov** [comment]
Thank you for the request.
I think MD also can be applied to commit descriptions (as an option).
MD rendering is in my list, but it's delayed because usually there are features/bugs with a higher priority.

**Comment by clounie** [comment]
I'd actually add to that ^.

Having a markdown preview available in the diff would be awesome. Not "diff markdown" - just being able to see what the new version looks like.

**Comment by mika76** [comment]
👍 for this - pretty hard to read some readme files 😆

**Comment by DanPristupov** [comment]
The problem is that readme.md on github != markdown. So, the majority of fancy readme files (i.e. most of popular repositories) won't be displayed same way as users expect.

**Comment by mika76** [comment]
Yeah I can understand - although getting even basic markdown would be an improvement
Here's some interesting repos: 
- https://guides.github.com/features/mastering-markdown/
- https://github.github.com/gfm/ (actual spec it seems)
- https://github.com/github/markup - this could be useful for you to determin which markdown is being used
- https://github.com/joeyespo/grip - python lib for rendering github markdown
- https://developer.github.com/v3/markdown/ - **this is cool** - github seems to have an api for rendering it's markdown

Otherwise lots of interesting posts at https://stackoverflow.com/questions/7694887/is-there-a-command-line-utility-for-rendering-github-flavored-markdown

**Comment by DanPristupov** [comment]
Hi. Finally I have some news. In Fork 1.0.86 we introduced readme.md rendering  🎉.

<img width="1015" alt="Screenshot 2019-11-08 at 18 28 04" src="https://user-images.githubusercontent.com/618115/68497721-82e8ec00-0255-11ea-9937-d4d8e4ca6cff.png">

**Comment by jbergstroem** [comment]
Holy smokes, batman! Thanks for the work.
