### ISSUE TITLE
[Bug] Checking out remote branch and pushing creates new branch with different case

### ISSUE THREAD

**Issue by ChrisRobbers** [ForkIssues/Tracker#906]
We are using the "git flow" naming system, and most of our branches are named like `feature/JIRA-12345-some-description`. So in fork 1.44.0.0 Windows client I have a "folder" that is named `feature` with all those branches grouped under it.

I checked out a new remote branch that was named `Feature/JIRA-12345-some-description` (note uppercase first letter), and made some commits, and when I went to push it back to remote I noticed it wanted me to create a new tracking branch named `feature/...`. I pushed it and it created a new remote branch (git I guess is case-sensitive for branch names).

It seems to me that fork should have recognized the difference in casing here rather than grouping with case-insensitive rules and then creating a new branch based on the (incorrect) lower-case version naming.

**Comment by DanPristupov** [comment]
This happens because you have case-insensitive file system.

> It seems to me that fork should have ... then creating a new branch based on the (incorrect) lower-case version naming.

This is **impossible** because you already have the `.git/refs/heads/feature` (not `Feature`!) folder. You can't create both `feature` and `Feature` folders on your computer.
This is how git works.

Similar topic: https://github.com/ForkIssues/Tracker/issues/670

**Comment by ChrisRobbers** [comment]
Makes sense, thank you for that information.
