### ISSUE TITLE
"Filter by Active Branch" button doesn't disables when filtering by other branch

### ISSUE THREAD

**Issue by ldipenti** [ForkIssues/Tracker#919]
Hello,

I've found an issue on the branch filter feature. Steps to reproduce:

1. Activate "filter by active branch" button on the top
2. Activate "Show only commits for X branch" button on the branch list on the left panel.
3. Check that "filter by active branch" button still shows active even though the filter is correctly showing the branch selected on the previous step.

I believe a good UX would be to link that top filter button to just filtering by active branch, and not to "show itself active when any filter is active".

**Comment by DanPristupov** [comment]
Well, this button is intended to show that you have a filter.

When no filter it quickly sets filter on the current branch
When there's already a filter, it removes it

**Comment by ldipenti** [comment]
Ok, sorry. I understood it like a shortcut to set the active branch filter, useful to switch back and forth between any other branch and the active. The visual element is similar to what a "branch_name + filter_icon" combination makes on every left panel row, that's why my confusion.
Feel free to close this if what I understood doesn't make any sense :)
Thanks!

**Comment by DanPristupov** [comment]
Initially this button was added because sometimes people set filter unintentionally and got very confused when they didn't see all the commits. Almost every day I was asked why Fork shows only some commits. We added this indicator to make visible, that user has a filter. Then we decided to also add some useful filter related action on it, that's why now it sets filter on current branch.

May be we can forget about this and redesign it from scratch, but I don't know how.

**Comment by ldipenti** [comment]
I find it really useful to be able to quickly filter by the active branch, as it avoids me to search for the per-branch filter on the (very long) branches list on the left, so I find that a very good UI design. Please don't take it out! :)
