### ISSUE TITLE
No longer showing changes if remote origin/master is ahead.

### ISSUE THREAD

**Issue by tictok** [ForkIssues/Tracker#92]
Use and love Fork daily on both my desktop Mac and Mac Book Pro. However, recently it appears to have to stopped picking up and showing changes in remote origin/master.

It will show me how far ahead my local master is, but doesn't give any indication that I might be behind the remote, unless I pull (or remove and then re-add the repo to Fork). If I pull, any changes that need to come through do so. Refreshing doesn't seem to do the trick either.

How often is it supposed to check? It might be just me, but sure that used to work okay. 
Currently using the most recent version of Fork on both macs, with Forks own instance of Git.

Not sure if it makes any difference, but I currently store most of my active repos on BitBucket so I can use their pipeline feature.

Thanks!

**Comment by DanPristupov** [comment]
Hi @tictok,

I'm not sure I understand the problem clearly. I guess you expect Fork to check changes in your remote repositories automatically?
- Fork does NOT fetch automatically YET and you should run fetch (or pull, which is fetch+merge) manually. Automatic fetch is in my todo list, BTW.
- Probably, this problem has appeared recently because you decided to switch from other git client which previously fetched new commits in the background.

Please let me know if I'm missing something.

**Comment by tictok** [comment]
Hi - thanks for replying.

I've used a few clients and CLI over the years, but for the best park of a year or so have settled on Fork.

Maybe I'm missing something. I'm was sure Fork used to do this!  i.e. If one day I worked elsewhere on my laptop, committed and pushed some changes, then the next day my desktop machine would have already fetched and shown me how many commits behind it is - making it obvious I needed to pull.

Apologies if Fork has never done this. I must've been dreaming! But please consider it a feature request if that's the case.

Thanks for your time, and awesome app ;)

**Comment by DanPristupov** [comment]
I'm closing this as there is an automatic fetch issue already: https://github.com/ForkIssues/Tracker/issues/35
