### ISSUE TITLE
Cannot push changes in .github/workflows/ with GitHub OAuth

### ISSUE THREAD

**Issue by tofi86** [ForkIssues/Tracker#946]
I connected my Fork with GitHub O-Auth and it worked great so far.

However, after enabling GitHub Actions in one of my repos through the web editor, I am not able to push changes to the workflow config files located at `.github/workflows/`. The following error message is shown:

```
Pushing to https://github.com/tofi86/universalJavaApplicationStub.git
Enumerating objects: 9, done.
Delta compression using up to 4 threads
Total 5 (delta 3), reused 0 (delta 0)
POST git-receive-pack (973 bytes)
remote: Resolving deltas:   0% (0/3)        
remote: Resolving deltas:  33% (1/3)        
remote: Resolving deltas:  66% (2/3)        
remote: Resolving deltas: 100% (3/3)        
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.        
To https://github.com/tofi86/universalJavaApplicationStub.git
 ! [remote rejected] develop → develop (refusing to allow an OAuth App to create or update workflow `.github/workflows/test.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/tofi86/universalJavaApplicationStub.git'
```

I am able to push these changes from the commandline via SSH without any problem.

I guess you will have to enable new OAuth permissions for GitHub Actions (workflows).

Best,
Tobias

**Comment by DanPristupov** [comment]
Looks like GitHub introduced new 'wofkflow' scope: https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#available-scopes

I will add this in the next update.

**Comment by tofi86** [comment]
Awesome, thanks! 👏

**Comment by thomthom** [comment]
Is there a need to log this in the Windows tracker as well? Or are both platforms kept in sync?

**Comment by DanPristupov** [comment]
Windows and mac versions are independent.

**Comment by thomthom** [comment]
> Windows and mac versions are independent.

That's a little strange, since you buy a license that works for both. And I don't see any reason why you would want a feature on one platform and not another. I use both Windows and Mac, when switching between platforms I'd still want my Git client to operate the same (minor OS UI differences aside.)

**Comment by damies13** [comment]
I am getting this error in Fork Version 2.39.1 on Mac

> ! [remote rejected]   <local branch name> → <remote same name> (refusing to allow an OAuth App to create or update workflow `.github/workflows/Regression_Tests.yml` without `workflow` scope)

Has something regressed? or is there a setting I need to enable somewhere? I can't find any documentation or help for this issue other than this issue.

**Comment by DanPristupov** [comment]
@damies13 I checked the source code, Fork does request `workflow` scope: `repo user admin:public_key notifications workflow`.

Did you log in to Fork -> Accounts -> GitHub?

**Comment by damies13** [comment]
This is what I have on that screen:
<img width="904" alt="Screenshot 2024-02-16 at 10 35 03 pm" src="https://github.com/fork-dev/Tracker/assets/15232871/cf367b48-9776-470c-b723-770efe106d10">

I don't see any settings I can change or how I can logout/login? I have not changed that since I started using Fork. but I only use on my Mac laptop, so only use Fork occasionally, most of my development is done on a Linux machine, I mostly only use my Mac when traveling.

I've worked around it for now using the github desktop app, but it's an awful git client, Fork is much nicer to use 👍
