### ISSUE TITLE
Option for licensing - Setapp

### ISSUE THREAD

**Issue by rbukovansky** [ForkIssues/Tracker#962]
Hi Dan,
have you thought about licensing Fork via Setapp ("Spotify for apps" on Mac)?
https://setapp.com

Thanks,
Richard

**Comment by DanPristupov** [comment]
I don't like subscriptions.

**Comment by rbukovansky** [comment]
Me neither, but it seems like it will be our future... 🤷🏻‍♂️

But OK...

**Comment by DanPristupov** [comment]
> it seems like it will be our future

Only if we support it ourselves ☝️

**Comment by carlosefonseca** [comment]
Hi!, just a thought… Many Setapp apps have both licensing models. I have a Setapp subscription and there's a git client there (not as good, obviously). I haven't paid for the Fork license yet but if I was using it through Setapp you'd already be getting some from my usage. And I bet I'm not the only one. You wouldn't be enforcing a subscription on people, but allowing people who already have Setapp to contribute.
(I'm not taking in consideration the work required to support both payment methods and I have no idea how much would Setapp bring, or even when it would match the price per user you're asking now).

Btw, I appreciate you not going with subscriptions, I left Tower.app because of the crazy amount they were asking for the subscription… 🙄 

Thanks

Edit: I've since purchased Fork 🙂

**Comment by requilence** [comment]
@DanPristupov [Setapp](https://setapp.com/developers) has a pretty fair model in my opinion. I have their subscription for a long time.
Apps that I used most will get a big part of the monthly fee. And in case of Fork, it will get a big part for sure, as I use it a lot :)

Please, if it is possible, make more research on it. As @carlosefonseca said a lot of apps listed in the Setapp also have another licensing model. And in the case, I already have the Setapp subscription and will use Fork through it it will be win-win for both user and developer(you), as you will get much bigger lifetime value
