### ISSUE TITLE
Incorrect duplicate line when resolving merge conflict in Fork

### ISSUE THREAD

**Issue by KirillOsenkov** [ForkIssues/Tracker#971]
Repro:

1. git clone https://github.com/KirillOsenkov/fork1
2. git checkout branch2
3. git merge master

Open the repo in fork and try to resolve the merge conflict in m.txt using Fork:

![image](https://user-images.githubusercontent.com/679326/79186569-dc3de400-7dce-11ea-864b-8d0efd80998a.png)

The last line is duplicated (and it's wrong)

**Comment by KirillOsenkov** [comment]
I also saw a lot of weirdness around this scenario when doing the real world merge:

1. some submodules from the .gitmodule file were deleted in the merge commit
2. since the merge was interrupted by a conflict, some files and submodules were unstaged and I had to manually run git submodule update --init --recursive before staging all and committing the merge commit
3. I saw an error that it was unable to create a merge commit - I wish I had taken a screenshot of it. Now I can't reproduce unfortunately.

**Comment by KirillOsenkov** [comment]
I think it was something about the lock file being open... but I didn't have any other app working with this repo (except for terminal). Can't reproduce now unfortunately.

**Comment by DanPristupov** [comment]
Thank you for creating the sample repository. I reproduced the problem and will give you more details a bit later.

**Comment by DanPristupov** [comment]
This looks like a merge conflict case I haven't seen before. So, technically this is not a mistake/bug but an unhandled configuration. It must be very rare, because you are the first person who reported that after 1.5 years of the merger existence :).

I'll do my best to fix it in the next update. As for now, please resolve such files manually in any text editor (just remove the <<<< blocks).

**Comment by KirillOsenkov** [comment]
Thanks for looking! No rush. I’d be very curious about the technical details if you have them.

**Comment by DanPristupov** [comment]
Turned out it's a weird behavior in git (most likely a bug).

Some time ago I reported it to the git mailing list, but no one responded (https://public-inbox.org/git/CAKdzDnnE3cOsfdQ+HFY76kNB1W2sSm-5EyY7JDe=MsvH4dBZpw@mail.gmail.com/T/#u).

So, I had to make Fork recognize the incorrect merge diff and 'fix' it.

FYI, here is how the correct result will look like in the upcoming 2.22:

<img width="1015" alt="Screenshot 2022-09-13 at 15 00 19" src="https://user-images.githubusercontent.com/618115/189964867-8b0abeee-8574-4e7d-9929-a45cad717569.png">

Once again, thank you very much for reporting that bug 👍

**Comment by KirillOsenkov** [comment]
@dscho we think it's a bug in Git, we reported it to the mailing list, but saw no response. Perhaps you could help move this forward?

**Comment by dscho** [comment]
@KirillOsenkov unfortunately, right now I am _swamped_. The safest bet is that other Git core contributors are also playing catch-up after [Git Merge](https://git-merge.com/), and/or busy with preparing for Git v2.38.0 which [is due Oct 3rd](https://tinyurl.com/gitcal).

Maybe reply on the mailing list with a gentle ping after v2.38.0 is out? Chances are that this is a really trivial bug in some diff post-processing, but even _that_ investigation is outside my reach right now.

**Comment by KirillOsenkov** [comment]
No problem, we'll try again later, thanks for responding!
