### ISSUE TITLE
Fork should do a better job detecting configuration problems

### ISSUE THREAD

**Issue by radianttap** [ForkIssues/Tracker#98]
Something suddenly got really hosed with Fork. It fails to recognize any git repo on my Mac.

When I try to open existing repo from the list, It gives me "Repository not found" alert. If I try to do File/Open it tells me it's not a repo and do I want to init.

Repo is there, works in terminal and Source Tree, as it should.

**Comment by radianttap** [comment]
Reason:
If you had Xcode 8 as Xcode.app and also Xcode 9 as Xcode-beta.app. Xcode.app was selected for command-line tools in Preferences.

When GM appeared you rename Xcode.app to Xcode-8.app, delete the beta and install the GM which is now Xcode.app. This will screw up the command line settings and the drop-down in Xcode preferences will have nothing selected.

Choosing one of the available options (Xcode 9 or Xcode 8.3.3) resolves the problem.

**Comment by radianttap** [comment]
Fork should do a better job of detecting that it's actually missing `git` executable as these alerts are really confusing.

**Comment by DanPristupov** [comment]
It took me some time to understand what has happened. It turned out that problem was related to Xcode 9 which blocked access to git instance until user open Xcode 9 and confirm user agreement.

Yes, Fork should do a better job detecting user problems indeed. I renamed this topic to 'Fork should do a better job detecting configuration problems'.

So, here what I've done to prevent such (or similar) cases:
- Now Fork detects if git is missed (i.e. the file is deleted or moved) and switch to inner git instance automatically. This helps when user removes git, which was installed with `brew`, but doesn't help when the executable file exists, but is blocked (like in the Xcode9 case).
- In order to be able to detect rare cases I updated Fork to be able to recognise different types of git errors and show contextual error reports.
- When such a problem appears, user will see an error window with detailed description and additional help buttons: `Switch to Fork git` or to `Open Xcode`.
![2017-09-20 at 15 33](https://user-images.githubusercontent.com/618115/30647154-31ff1d0a-9e1b-11e7-96ee-aacbfba4a2ad.png)
- Released Fork 1.56 where Fork git in the default git instance, to prevent new users from struggling with this particular problem.
- In the future I will handle all 'unclear' errors like this and show quick action buttons which will help to solve the problem.
- I renamed this topic to 'Fork should do a better job detecting configuration problems'.

**Comment by radianttap** [comment]
Amazing response! 👏🏻

**Comment by radianttap** [comment]
BTW...

> It took me some time to understand what has happened. It turned out that problem was related to Xcode 9 which blocked access to git instance until user open Xcode 9 and confirm user agreement.

This was not the case with me. I did open the Xcode 9 and accepted all there was to accept, installed components. I was working in it for few hours, building, running in Sim etc. Only the command-line tools preference setting was in limbo state, with nothing selected.

Writing this just in case there's another edge case to figure out.
